/*
 * Copyright (C) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {loadAndSetUpUiTest } from '@ohos.UiTest';
import abilityDelegatorRegistry from '@ohos.app.ability.abilityDelegatorRegistry';
import  hilog  from '@ohos.hilog';
import { BusinessError } from '@ohos.base';
import access from '@ohos.bluetooth.access';
import { Component, Driver, ON, On, MatchPattern, MouseButton, WindowMode, UIElementInfo, UiDirection, PointerMatrix, DisplayRotation, loadAndSetUpUiTest } from '@ohos.UiTest';

const abilityDelegator:abilityDelegatorRegistry.AbilityDelegator = abilityDelegatorRegistry.getAbilityDelegator();
let domain: number = 0x0000; //日志标识,0x0000作为测试框架的业务标识
let tag: string = 'bt003UtilsTag'; //日志标识字符串,作为tag标识当前runner类下的测试行为
// class Utils{
  export default class Utils{
  static isLoadAndSetupUiTest = false;

  static async loadAndSetupUiTest() : Promise<boolean> {
    return new Promise<boolean>((resolve, reject) => {
      hilog.info(domain, tag, `loadAndSetupUiTest, isLoadAndSetupUiTest: ${JSON.stringify(Utils.isLoadAndSetupUiTest)}`);
      try {
        if (!Utils.isLoadAndSetupUiTest) {
          loadAndSetUpUiTest();
          hilog.info(domain, tag, `loadAndSetupUiTest, success`);
          Utils.isLoadAndSetupUiTest = true;
        }
        resolve(true)
      }catch(error: Error) {
        hilog.info(domain, tag, `UiTestCase, start abilityFailed: ${JSON.stringify(error)}`);
        reject(error)
      }
    })
  }

  static async msSleep(count:int) : Promise<int> {
    return new Promise<int>((resolve, reject) => {
      setTimeout(() => {
        resolve(0)
      }, count)
    })
  }

  static async clickRequestPermission(mess: string) : Promise<void> {
    hilog.info(domain, tag, 'clickRequestPermission start');
    try {
      let driver = Driver.create();
      let permissionButton = await driver.waitForComponent(ON.text(mess, MatchPattern.EQUALS), 1000);
      if (permissionButton != null) {
        await permissionButton.click();
        hilog.info(domain, tag, 'clickRequestPermission end');
      }
    } catch (err: BusinessError) {
      hilog.info(domain, tag, 'clickRequestPermission get err:' + err);
    }
  }

  static async closeBluetooth() : Promise<void> {
    let state: access.BluetoothState = access.getState();
    switch(state){
      case access.BluetoothState.STATE_OFF:
        hilog.info(domain, tag, 'bt is turn off');
        break;
      case access.BluetoothState.STATE_TURNING_ON:
        access.disableBluetooth();
        await Utils.clickRequestPermission("关闭");
        await Utils.msSleep(3000);
        let state1: access.BluetoothState = access.getState();
        hilog.info(domain, tag, 'disableBluetooth after getState result:' + state1);
        break;
      case access.BluetoothState.STATE_ON:
        access.disableBluetooth();
        await Utils.clickRequestPermission("关闭");
        await Utils.msSleep(3000);
        let state2: access.BluetoothState = access.getState();
        hilog.info(domain, tag, 'disableBluetooth after getState result:' + state2);
        break;
      case access.BluetoothState.STATE_TURNING_OFF:
        hilog.info(domain, tag, 'bt is turning off');
        await Utils.msSleep(3000);
        break;
      default:
        hilog.info(domain, tag, 'getState get error:' + state);
    }
  }
}