/*
 * Copyright (C) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import hilog from '@ohos.hilog';
import { describe, beforeAll, beforeEach, afterEach, afterAll, it, expect, TestType, Level, Size } from '@ohos/hypium';

import {checkError, createProgram, getColorUint8Array,clear,WEBGL2_FRAGMENT_SHADER_DEMO} from './WebGL2';


export default function webgl2_enum() {
    
	describe('webgl2_enum', function () {
        let gl = global.gl2;
        // Defines a test suite. Two parameters are supported: test suite name and test suite function.
        beforeAll(function () {
            hilog.info(0x0000, 'testTag', '%{public}s', 'webgl1_test_01 start');
            // Presets an action, which is performed only once before all test cases of the test suite start.
            // This API supports only one parameter: preset action function.
        });
        beforeEach(function () {
            // Presets an action, which is performed before each unit test case starts.
            // The number of execution times is the same as the number of test cases defined by **it**.
            // This API supports only one parameter: preset action function.
            checkError(gl);
        });
        afterEach(function () {
            // Presets a clear action, which is performed after each unit test case ends.
            // The number of execution times is the same as the number of test cases defined by **it**.
            // This API supports only one parameter: clear action function.
            checkError(gl);
        });
        afterAll(function () {
            // Presets a clear action, which is performed after all test cases of the test suite end.
            // This API supports only one parameter: clear action function.
            hilog.info(0x0000, 'testTag', '%{public}s', 'webgl1_test_01 end');
        });
        /**
         * @tc.number GRAPHIC_FUNCTION_JS_WEBGL_ENUM_0001
         * @tc.name webgl2_test_enum
         * @tc.desc Test enum.
         */
        it('webgl2_test_enum', TestType.FUNCTION | Size.MEDIUMTEST | Level.LEVEL0, async function (done) {
            console.info("webgltest [webgl2_test_enum] enum");
            console.info("webgltest gl.READ_BUFFER = ", gl.READ_BUFFER);
            expect(gl.READ_BUFFER).assertEqual(0x0C02);
            console.info("webgltest gl.UNPACK_ROW_LENGTH = ", gl.UNPACK_ROW_LENGTH);
            expect(gl.UNPACK_ROW_LENGTH).assertEqual(0x0CF2);
            console.info("webgltest gl.UNPACK_SKIP_ROWS = ", gl.UNPACK_SKIP_ROWS);
            expect(gl.UNPACK_SKIP_ROWS).assertEqual(0x0CF3);
            console.info("webgltest gl.UNPACK_SKIP_PIXELS = ", gl.UNPACK_SKIP_PIXELS);
            expect(gl.UNPACK_SKIP_PIXELS).assertEqual(0x0CF4);
            console.info("webgltest gl.PACK_ROW_LENGTH = ", gl.PACK_ROW_LENGTH);
            expect(gl.PACK_ROW_LENGTH).assertEqual(0x0D02);
            console.info("webgltest gl.PACK_SKIP_ROWS = ", gl.PACK_SKIP_ROWS);
            expect(gl.PACK_SKIP_ROWS).assertEqual(0x0D03);
            console.info("webgltest gl.PACK_SKIP_PIXELS = ", gl.PACK_SKIP_PIXELS);
            expect(gl.PACK_SKIP_PIXELS).assertEqual(0x0D04);
            console.info("webgltest gl.COLOR = ", gl.COLOR);
            expect(gl.COLOR).assertEqual(0x1800);
            console.info("webgltest gl.DEPTH = ", gl.DEPTH);
            expect(gl.DEPTH).assertEqual(0x1801);
            console.info("webgltest gl.STENCIL = ", gl.STENCIL);
            expect(gl.STENCIL).assertEqual(0x1802);
            console.info("webgltest gl.RED = ", gl.RED);
            expect(gl.RED).assertEqual(0x1903);
            console.info("webgltest gl.RGB8 = ", gl.RGB8);
            expect(gl.RGB8).assertEqual(0x8051);
            console.info("webgltest gl.RGBA8 = ", gl.RGBA8);
            expect(gl.RGBA8).assertEqual(0x8058);
            console.info("webgltest gl.RGB10_A2 = ", gl.RGB10_A2);
            expect(gl.RGB10_A2).assertEqual(0x8059);
            console.info("webgltest gl.TEXTURE_BINDING_3D = ", gl.TEXTURE_BINDING_3D);
            expect(gl.TEXTURE_BINDING_3D).assertEqual(0x806A);
            console.info("webgltest gl.UNPACK_SKIP_IMAGES = ", gl.UNPACK_SKIP_IMAGES);
            expect(gl.UNPACK_SKIP_IMAGES).assertEqual(0x806D);
            console.info("webgltest gl.UNPACK_IMAGE_HEIGHT = ", gl.UNPACK_IMAGE_HEIGHT);
            expect(gl.UNPACK_IMAGE_HEIGHT).assertEqual(0x806E);
            console.info("webgltest gl.TEXTURE_3D = ", gl.TEXTURE_3D);
            expect(gl.TEXTURE_3D).assertEqual(0x806F);
            console.info("webgltest gl.TEXTURE_WRAP_R = ", gl.TEXTURE_WRAP_R);
            expect(gl.TEXTURE_WRAP_R).assertEqual(0x8072);
            console.info("webgltest gl.MAX_3D_TEXTURE_SIZE = ", gl.MAX_3D_TEXTURE_SIZE);
            expect(gl.MAX_3D_TEXTURE_SIZE).assertEqual(0x8073);
            console.info("webgltest gl.UNSIGNED_INT_2_10_10_10_REV = ", gl.UNSIGNED_INT_2_10_10_10_REV);
            expect(gl.UNSIGNED_INT_2_10_10_10_REV).assertEqual(0x8368);
            console.info("webgltest gl.MAX_ELEMENTS_VERTICES = ", gl.MAX_ELEMENTS_VERTICES);
            expect(gl.MAX_ELEMENTS_VERTICES).assertEqual(0x80E8);
            console.info("webgltest gl.MAX_ELEMENTS_INDICES = ", gl.MAX_ELEMENTS_INDICES);
            expect(gl.MAX_ELEMENTS_INDICES).assertEqual(0x80E9);
            console.info("webgltest gl.TEXTURE_MIN_LOD = ", gl.TEXTURE_MIN_LOD);
            expect(gl.TEXTURE_MIN_LOD).assertEqual(0x813A);
            console.info("webgltest gl.TEXTURE_MAX_LOD = ", gl.TEXTURE_MAX_LOD);
            expect(gl.TEXTURE_MAX_LOD).assertEqual(0x813B);
            console.info("webgltest gl.TEXTURE_BASE_LEVEL = ", gl.TEXTURE_BASE_LEVEL);
            expect(gl.TEXTURE_BASE_LEVEL).assertEqual(0x813C);
            console.info("webgltest gl.TEXTURE_MAX_LEVEL = ", gl.TEXTURE_MAX_LEVEL);
            expect(gl.TEXTURE_MAX_LEVEL).assertEqual(0x813D);
            console.info("webgltest gl.MIN = ", gl.MIN);
            expect(gl.MIN).assertEqual(0x8007);
            console.info("webgltest gl.MAX = ", gl.MAX);
            expect(gl.MAX).assertEqual(0x8008);
            console.info("webgltest gl.DEPTH_COMPONENT24 = ", gl.DEPTH_COMPONENT24);
            expect(gl.DEPTH_COMPONENT24).assertEqual(0x81A6);
            console.info("webgltest gl.MAX_TEXTURE_LOD_BIAS = ", gl.MAX_TEXTURE_LOD_BIAS);
            expect(gl.MAX_TEXTURE_LOD_BIAS).assertEqual(0x84FD);
            console.info("webgltest gl.TEXTURE_COMPARE_MODE = ", gl.TEXTURE_COMPARE_MODE);
            expect(gl.TEXTURE_COMPARE_MODE).assertEqual(0x884C);
            console.info("webgltest gl.TEXTURE_COMPARE_FUNC = ", gl.TEXTURE_COMPARE_FUNC);
            expect(gl.TEXTURE_COMPARE_FUNC).assertEqual(0x884D);
            console.info("webgltest gl.CURRENT_QUERY = ", gl.CURRENT_QUERY);
            expect(gl.CURRENT_QUERY).assertEqual(0x8865);
            console.info("webgltest gl.QUERY_RESULT = ", gl.QUERY_RESULT);
            expect(gl.QUERY_RESULT).assertEqual(0x8866);
            console.info("webgltest gl.QUERY_RESULT_AVAILABLE = ", gl.QUERY_RESULT_AVAILABLE);
            expect(gl.QUERY_RESULT_AVAILABLE).assertEqual(0x8867);
            console.info("webgltest gl.STREAM_READ = ", gl.STREAM_READ);
            expect(gl.STREAM_READ).assertEqual(0x88E1);
            console.info("webgltest gl.STREAM_COPY = ", gl.STREAM_COPY);
            expect(gl.STREAM_COPY).assertEqual(0x88E2);
            console.info("webgltest gl.STATIC_READ = ", gl.STATIC_READ);
            expect(gl.STATIC_READ).assertEqual(0x88E5);
            console.info("webgltest gl.STATIC_COPY = ", gl.STATIC_COPY);
            expect(gl.STATIC_COPY).assertEqual(0x88E6);
            console.info("webgltest gl.DYNAMIC_READ = ", gl.DYNAMIC_READ);
            expect(gl.DYNAMIC_READ).assertEqual(0x88E9);
            console.info("webgltest gl.DYNAMIC_COPY = ", gl.DYNAMIC_COPY);
            expect(gl.DYNAMIC_COPY).assertEqual(0x88EA);
            console.info("webgltest gl.MAX_DRAW_BUFFERS = ", gl.MAX_DRAW_BUFFERS);
            expect(gl.MAX_DRAW_BUFFERS).assertEqual(0x8824);
            console.info("webgltest gl.DRAW_BUFFER0 = ", gl.DRAW_BUFFER0);
            expect(gl.DRAW_BUFFER0).assertEqual(0x8825);
            console.info("webgltest gl.DRAW_BUFFER1 = ", gl.DRAW_BUFFER1);
            expect(gl.DRAW_BUFFER1).assertEqual(0x8826);
            console.info("webgltest gl.DRAW_BUFFER2 = ", gl.DRAW_BUFFER2);
            expect(gl.DRAW_BUFFER2).assertEqual(0x8827);
            console.info("webgltest gl.DRAW_BUFFER3 = ", gl.DRAW_BUFFER3);
            expect(gl.DRAW_BUFFER3).assertEqual(0x8828);
            console.info("webgltest gl.DRAW_BUFFER4 = ", gl.DRAW_BUFFER4);
            expect(gl.DRAW_BUFFER4).assertEqual(0x8829);
            console.info("webgltest gl.DRAW_BUFFER5 = ", gl.DRAW_BUFFER5);
            expect(gl.DRAW_BUFFER5).assertEqual(0x882A);
            console.info("webgltest gl.DRAW_BUFFER6 = ", gl.DRAW_BUFFER6);
            expect(gl.DRAW_BUFFER6).assertEqual(0x882B);
            console.info("webgltest gl.DRAW_BUFFER7 = ", gl.DRAW_BUFFER7);
            expect(gl.DRAW_BUFFER7).assertEqual(0x882C);
            console.info("webgltest gl.DRAW_BUFFER8 = ", gl.DRAW_BUFFER8);
            expect(gl.DRAW_BUFFER8).assertEqual(0x882D);
            console.info("webgltest gl.DRAW_BUFFER9 = ", gl.DRAW_BUFFER9);
            expect(gl.DRAW_BUFFER9).assertEqual(0x882E);
            console.info("webgltest gl.DRAW_BUFFER10 = ", gl.DRAW_BUFFER10);
            expect(gl.DRAW_BUFFER10).assertEqual(0x882F);
            console.info("webgltest gl.DRAW_BUFFER11 = ", gl.DRAW_BUFFER11);
            expect(gl.DRAW_BUFFER11).assertEqual(0x8830);
            console.info("webgltest gl.DRAW_BUFFER12 = ", gl.DRAW_BUFFER12);
            expect(gl.DRAW_BUFFER12).assertEqual(0x8831);
            console.info("webgltest gl.DRAW_BUFFER13 = ", gl.DRAW_BUFFER13);
            expect(gl.DRAW_BUFFER13).assertEqual(0x8832);
            console.info("webgltest gl.DRAW_BUFFER14 = ", gl.DRAW_BUFFER14);
            expect(gl.DRAW_BUFFER14).assertEqual(0x8833);
            console.info("webgltest gl.DRAW_BUFFER15 = ", gl.DRAW_BUFFER15);
            expect(gl.DRAW_BUFFER15).assertEqual(0x8834);
            console.info("webgltest gl.MAX_FRAGMENT_UNIFORM_COMPONENTS = ", gl.MAX_FRAGMENT_UNIFORM_COMPONENTS);
            expect(gl.MAX_FRAGMENT_UNIFORM_COMPONENTS).assertEqual(0x8B49);
            console.info("webgltest gl.MAX_VERTEX_UNIFORM_COMPONENTS = ", gl.MAX_VERTEX_UNIFORM_COMPONENTS);
            expect(gl.MAX_VERTEX_UNIFORM_COMPONENTS).assertEqual(0x8B4A);
            console.info("webgltest gl.SAMPLER_3D = ", gl.SAMPLER_3D);
            expect(gl.SAMPLER_3D).assertEqual(0x8B5F);
            console.info("webgltest gl.SAMPLER_2D_SHADOW = ", gl.SAMPLER_2D_SHADOW);
            expect(gl.SAMPLER_2D_SHADOW).assertEqual(0x8B62);
            console.info("webgltest gl.FRAGMENT_SHADER_DERIVATIVE_HINT = ", gl.FRAGMENT_SHADER_DERIVATIVE_HINT);
            expect(gl.FRAGMENT_SHADER_DERIVATIVE_HINT).assertEqual(0x8B8B);
            console.info("webgltest gl.PIXEL_PACK_BUFFER = ", gl.PIXEL_PACK_BUFFER);
            expect(gl.PIXEL_PACK_BUFFER).assertEqual(0x88EB);
            console.info("webgltest gl.PIXEL_UNPACK_BUFFER = ", gl.PIXEL_UNPACK_BUFFER);
            expect(gl.PIXEL_UNPACK_BUFFER).assertEqual(0x88EC);
            console.info("webgltest gl.PIXEL_PACK_BUFFER_BINDING = ", gl.PIXEL_PACK_BUFFER_BINDING);
            expect(gl.PIXEL_PACK_BUFFER_BINDING).assertEqual(0x88ED);
            console.info("webgltest gl.PIXEL_UNPACK_BUFFER_BINDING = ", gl.PIXEL_UNPACK_BUFFER_BINDING);
            expect(gl.PIXEL_UNPACK_BUFFER_BINDING).assertEqual(0x88EF);
            console.info("webgltest gl.FLOAT_MAT2x3 = ", gl.FLOAT_MAT2x3);
            expect(gl.FLOAT_MAT2x3).assertEqual(0x8B65);
            console.info("webgltest gl.FLOAT_MAT2x4 = ", gl.FLOAT_MAT2x4);
            expect(gl.FLOAT_MAT2x4).assertEqual(0x8B66);
            console.info("webgltest gl.FLOAT_MAT3x2 = ", gl.FLOAT_MAT3x2);
            expect(gl.FLOAT_MAT3x2).assertEqual(0x8B67);
            console.info("webgltest gl.FLOAT_MAT3x4 = ", gl.FLOAT_MAT3x4);
            expect(gl.FLOAT_MAT3x4).assertEqual(0x8B68);
            console.info("webgltest gl.FLOAT_MAT4x2 = ", gl.FLOAT_MAT4x2);
            expect(gl.FLOAT_MAT4x2).assertEqual(0x8B69);
            console.info("webgltest gl.FLOAT_MAT4x3 = ", gl.FLOAT_MAT4x3);
            expect(gl.FLOAT_MAT4x3).assertEqual(0x8B6A);
            console.info("webgltest gl.SRGB = ", gl.SRGB);
            expect(gl.SRGB).assertEqual(0x8C40);
            console.info("webgltest gl.SRGB8 = ", gl.SRGB8);
            expect(gl.SRGB8).assertEqual(0x8C41);
            console.info("webgltest gl.SRGB8_ALPHA8 = ", gl.SRGB8_ALPHA8);
            expect(gl.SRGB8_ALPHA8).assertEqual(0x8C43);
            console.info("webgltest gl.COMPARE_REF_TO_TEXTURE = ", gl.COMPARE_REF_TO_TEXTURE);
            expect(gl.COMPARE_REF_TO_TEXTURE).assertEqual(0x884E);
            console.info("webgltest gl.RGBA32F = ", gl.RGBA32F);
            expect(gl.RGBA32F).assertEqual(0x8814);
            console.info("webgltest gl.RGB32F = ", gl.RGB32F);
            expect(gl.RGB32F).assertEqual(0x8815);
            console.info("webgltest gl.RGBA16F = ", gl.RGBA16F);
            expect(gl.RGBA16F).assertEqual(0x881A);
            console.info("webgltest gl.RGB16F = ", gl.RGB16F);
            expect(gl.RGB16F).assertEqual(0x881B);
            console.info("webgltest gl.VERTEX_ATTRIB_ARRAY_INTEGER = ", gl.VERTEX_ATTRIB_ARRAY_INTEGER);
            expect(gl.VERTEX_ATTRIB_ARRAY_INTEGER).assertEqual(0x88FD);
            console.info("webgltest gl.MAX_ARRAY_TEXTURE_LAYERS = ", gl.MAX_ARRAY_TEXTURE_LAYERS);
            expect(gl.MAX_ARRAY_TEXTURE_LAYERS).assertEqual(0x88FF);
            console.info("webgltest gl.MIN_PROGRAM_TEXEL_OFFSET = ", gl.MIN_PROGRAM_TEXEL_OFFSET);
            expect(gl.MIN_PROGRAM_TEXEL_OFFSET).assertEqual(0x8904);
            console.info("webgltest gl.MAX_PROGRAM_TEXEL_OFFSET = ", gl.MAX_PROGRAM_TEXEL_OFFSET);
            expect(gl.MAX_PROGRAM_TEXEL_OFFSET).assertEqual(0x8905);
            console.info("webgltest gl.MAX_VARYING_COMPONENTS = ", gl.MAX_VARYING_COMPONENTS);
            expect(gl.MAX_VARYING_COMPONENTS).assertEqual(0x8B4B);
            console.info("webgltest gl.TEXTURE_2D_ARRAY = ", gl.TEXTURE_2D_ARRAY);
            expect(gl.TEXTURE_2D_ARRAY).assertEqual(0x8C1A);
            console.info("webgltest gl.TEXTURE_BINDING_2D_ARRAY = ", gl.TEXTURE_BINDING_2D_ARRAY);
            expect(gl.TEXTURE_BINDING_2D_ARRAY).assertEqual(0x8C1D);
            console.info("webgltest gl.R11F_G11F_B10F = ", gl.R11F_G11F_B10F);
            expect(gl.R11F_G11F_B10F).assertEqual(0x8C3A);
            console.info("webgltest gl.UNSIGNED_INT_10F_11F_11F_REV = ", gl.UNSIGNED_INT_10F_11F_11F_REV);
            expect(gl.UNSIGNED_INT_10F_11F_11F_REV).assertEqual(0x8C3B);
            console.info("webgltest gl.RGB9_E5 = ", gl.RGB9_E5);
            expect(gl.RGB9_E5).assertEqual(0x8C3D);
            console.info("webgltest gl.UNSIGNED_INT_5_9_9_9_REV = ", gl.UNSIGNED_INT_5_9_9_9_REV);
            expect(gl.UNSIGNED_INT_5_9_9_9_REV).assertEqual(0x8C3E);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_BUFFER_MODE = ", gl.TRANSFORM_FEEDBACK_BUFFER_MODE);
            expect(gl.TRANSFORM_FEEDBACK_BUFFER_MODE).assertEqual(0x8C7F);
            console.info("webgltest gl.MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = ", gl.MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS);
            expect(gl.MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS).assertEqual(0x8C80);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_VARYINGS = ", gl.TRANSFORM_FEEDBACK_VARYINGS);
            expect(gl.TRANSFORM_FEEDBACK_VARYINGS).assertEqual(0x8C83);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_BUFFER_START = ", gl.TRANSFORM_FEEDBACK_BUFFER_START);
            expect(gl.TRANSFORM_FEEDBACK_BUFFER_START).assertEqual(0x8C84);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_BUFFER_SIZE = ", gl.TRANSFORM_FEEDBACK_BUFFER_SIZE);
            expect(gl.TRANSFORM_FEEDBACK_BUFFER_SIZE).assertEqual(0x8C85);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = ", gl.TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN);
            expect(gl.TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN).assertEqual(0x8C88);
            console.info("webgltest gl.RASTERIZER_DISCARD = ", gl.RASTERIZER_DISCARD);
            expect(gl.RASTERIZER_DISCARD).assertEqual(0x8C89);
            console.info("webgltest gl.MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = ", gl.MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS);
            expect(gl.MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS).assertEqual(0x8C8A);
            console.info("webgltest gl.MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = ", gl.MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS);
            expect(gl.MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS).assertEqual(0x8C8B);
            console.info("webgltest gl.INTERLEAVED_ATTRIBS = ", gl.INTERLEAVED_ATTRIBS);
            expect(gl.INTERLEAVED_ATTRIBS).assertEqual(0x8C8C);
            console.info("webgltest gl.SEPARATE_ATTRIBS = ", gl.SEPARATE_ATTRIBS);
            expect(gl.SEPARATE_ATTRIBS).assertEqual(0x8C8D);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_BUFFER = ", gl.TRANSFORM_FEEDBACK_BUFFER);
            expect(gl.TRANSFORM_FEEDBACK_BUFFER).assertEqual(0x8C8E);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_BUFFER_BINDING = ", gl.TRANSFORM_FEEDBACK_BUFFER_BINDING);
            expect(gl.TRANSFORM_FEEDBACK_BUFFER_BINDING).assertEqual(0x8C8F);
            console.info("webgltest gl.RGBA32UI = ", gl.RGBA32UI);
            expect(gl.RGBA32UI).assertEqual(0x8D70);
            console.info("webgltest gl.RGB32UI = ", gl.RGB32UI);
            expect(gl.RGB32UI).assertEqual(0x8D71);
            console.info("webgltest gl.RGBA16UI = ", gl.RGBA16UI);
            expect(gl.RGBA16UI).assertEqual(0x8D76);
            console.info("webgltest gl.RGB16UI = ", gl.RGB16UI);
            expect(gl.RGB16UI).assertEqual(0x8D77);
            console.info("webgltest gl.RGBA8UI = ", gl.RGBA8UI);
            expect(gl.RGBA8UI).assertEqual(0x8D7C);
            console.info("webgltest gl.RGB8UI = ", gl.RGB8UI);
            expect(gl.RGB8UI).assertEqual(0x8D7D);
            console.info("webgltest gl.RGBA32I = ", gl.RGBA32I);
            expect(gl.RGBA32I).assertEqual(0x8D82);
            console.info("webgltest gl.RGB32I = ", gl.RGB32I);
            expect(gl.RGB32I).assertEqual(0x8D83);
            console.info("webgltest gl.RGBA16I = ", gl.RGBA16I);
            expect(gl.RGBA16I).assertEqual(0x8D88);
            console.info("webgltest gl.RGB16I = ", gl.RGB16I);
            expect(gl.RGB16I).assertEqual(0x8D89);
            console.info("webgltest gl.RGBA8I = ", gl.RGBA8I);
            expect(gl.RGBA8I).assertEqual(0x8D8E);
            console.info("webgltest gl.RGB8I = ", gl.RGB8I);
            expect(gl.RGB8I).assertEqual(0x8D8F);
            console.info("webgltest gl.RED_INTEGER = ", gl.RED_INTEGER);
            expect(gl.RED_INTEGER).assertEqual(0x8D94);
            console.info("webgltest gl.RGB_INTEGER = ", gl.RGB_INTEGER);
            expect(gl.RGB_INTEGER).assertEqual(0x8D98);
            console.info("webgltest gl.RGBA_INTEGER = ", gl.RGBA_INTEGER);
            expect(gl.RGBA_INTEGER).assertEqual(0x8D99);
            console.info("webgltest gl.SAMPLER_2D_ARRAY = ", gl.SAMPLER_2D_ARRAY);
            expect(gl.SAMPLER_2D_ARRAY).assertEqual(0x8DC1);
            console.info("webgltest gl.SAMPLER_2D_ARRAY_SHADOW = ", gl.SAMPLER_2D_ARRAY_SHADOW);
            expect(gl.SAMPLER_2D_ARRAY_SHADOW).assertEqual(0x8DC4);
            console.info("webgltest gl.SAMPLER_CUBE_SHADOW = ", gl.SAMPLER_CUBE_SHADOW);
            expect(gl.SAMPLER_CUBE_SHADOW).assertEqual(0x8DC5);
            console.info("webgltest gl.UNSIGNED_INT_VEC2 = ", gl.UNSIGNED_INT_VEC2);
            expect(gl.UNSIGNED_INT_VEC2).assertEqual(0x8DC6);
            console.info("webgltest gl.UNSIGNED_INT_VEC3 = ", gl.UNSIGNED_INT_VEC3);
            expect(gl.UNSIGNED_INT_VEC3).assertEqual(0x8DC7);
            console.info("webgltest gl.UNSIGNED_INT_VEC4 = ", gl.UNSIGNED_INT_VEC4);
            expect(gl.UNSIGNED_INT_VEC4).assertEqual(0x8DC8);
            console.info("webgltest gl.INT_SAMPLER_2D = ", gl.INT_SAMPLER_2D);
            expect(gl.INT_SAMPLER_2D).assertEqual(0x8DCA);
            console.info("webgltest gl.INT_SAMPLER_3D = ", gl.INT_SAMPLER_3D);
            expect(gl.INT_SAMPLER_3D).assertEqual(0x8DCB);
            console.info("webgltest gl.INT_SAMPLER_CUBE = ", gl.INT_SAMPLER_CUBE);
            expect(gl.INT_SAMPLER_CUBE).assertEqual(0x8DCC);
            console.info("webgltest gl.INT_SAMPLER_2D_ARRAY = ", gl.INT_SAMPLER_2D_ARRAY);
            expect(gl.INT_SAMPLER_2D_ARRAY).assertEqual(0x8DCF);
            console.info("webgltest gl.UNSIGNED_INT_SAMPLER_2D = ", gl.UNSIGNED_INT_SAMPLER_2D);
            expect(gl.UNSIGNED_INT_SAMPLER_2D).assertEqual(0x8DD2);
            console.info("webgltest gl.UNSIGNED_INT_SAMPLER_3D = ", gl.UNSIGNED_INT_SAMPLER_3D);
            expect(gl.UNSIGNED_INT_SAMPLER_3D).assertEqual(0x8DD3);
            console.info("webgltest gl.UNSIGNED_INT_SAMPLER_CUBE = ", gl.UNSIGNED_INT_SAMPLER_CUBE);
            expect(gl.UNSIGNED_INT_SAMPLER_CUBE).assertEqual(0x8DD4);
            console.info("webgltest gl.UNSIGNED_INT_SAMPLER_2D_ARRAY = ", gl.UNSIGNED_INT_SAMPLER_2D_ARRAY);
            expect(gl.UNSIGNED_INT_SAMPLER_2D_ARRAY).assertEqual(0x8DD7);
            console.info("webgltest gl.DEPTH_COMPONENT32F = ", gl.DEPTH_COMPONENT32F);
            expect(gl.DEPTH_COMPONENT32F).assertEqual(0x8CAC);
            console.info("webgltest gl.DEPTH32F_STENCIL8 = ", gl.DEPTH32F_STENCIL8);
            expect(gl.DEPTH32F_STENCIL8).assertEqual(0x8CAD);
            console.info("webgltest gl.FLOAT_32_UNSIGNED_INT_24_8_REV = ", gl.FLOAT_32_UNSIGNED_INT_24_8_REV);
            expect(gl.FLOAT_32_UNSIGNED_INT_24_8_REV).assertEqual(0x8DAD);
            console.info("webgltest gl.FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = ", gl.FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING);
            expect(gl.FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING).assertEqual(0x8210);
            console.info("webgltest gl.FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = ", gl.FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE);
            expect(gl.FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE).assertEqual(0x8211);
            console.info("webgltest gl.FRAMEBUFFER_ATTACHMENT_RED_SIZE = ", gl.FRAMEBUFFER_ATTACHMENT_RED_SIZE);
            expect(gl.FRAMEBUFFER_ATTACHMENT_RED_SIZE).assertEqual(0x8212);
            console.info("webgltest gl.FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = ", gl.FRAMEBUFFER_ATTACHMENT_GREEN_SIZE);
            expect(gl.FRAMEBUFFER_ATTACHMENT_GREEN_SIZE).assertEqual(0x8213);
            console.info("webgltest gl.FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = ", gl.FRAMEBUFFER_ATTACHMENT_BLUE_SIZE);
            expect(gl.FRAMEBUFFER_ATTACHMENT_BLUE_SIZE).assertEqual(0x8214);
            console.info("webgltest gl.FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = ", gl.FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE);
            expect(gl.FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE).assertEqual(0x8215);
            console.info("webgltest gl.FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = ", gl.FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE);
            expect(gl.FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE).assertEqual(0x8216);
            console.info("webgltest gl.FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = ", gl.FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE);
            expect(gl.FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE).assertEqual(0x8217);
            console.info("webgltest gl.FRAMEBUFFER_DEFAULT = ", gl.FRAMEBUFFER_DEFAULT);
            expect(gl.FRAMEBUFFER_DEFAULT).assertEqual(0x8218);
            console.info("webgltest gl.DEPTH_STENCIL_ATTACHMENT = ", gl.DEPTH_STENCIL_ATTACHMENT);
            expect(gl.UNSIGNED_INT_24_8).assertEqual(0x84FA);
            console.info("webgltest gl.DEPTH24_STENCIL8 = ", gl.DEPTH24_STENCIL8);
            expect(gl.DEPTH24_STENCIL8).assertEqual(0x88F0);
            console.info("webgltest gl.UNSIGNED_NORMALIZED = ", gl.UNSIGNED_NORMALIZED);
            expect(gl.UNSIGNED_NORMALIZED).assertEqual(0x8C17);
            console.info("webgltest gl.DRAW_FRAMEBUFFER_BINDING = ", gl.DRAW_FRAMEBUFFER_BINDING);
            expect(gl.DRAW_FRAMEBUFFER_BINDING).assertEqual(0x8CA6); /* Same as FRAMEBUFFER_BINDING */
            console.info("webgltest gl.READ_FRAMEBUFFER = ", gl.READ_FRAMEBUFFER);
            expect(gl.READ_FRAMEBUFFER).assertEqual(0x8CA8);
            console.info("webgltest gl.DRAW_FRAMEBUFFER = ", gl.DRAW_FRAMEBUFFER);
            expect(gl.DRAW_FRAMEBUFFER).assertEqual(0x8CA9);
            console.info("webgltest gl.READ_FRAMEBUFFER_BINDING = ", gl.READ_FRAMEBUFFER_BINDING);
            expect(gl.READ_FRAMEBUFFER_BINDING).assertEqual(0x8CAA);
            console.info("webgltest gl.RENDERBUFFER_SAMPLES = ", gl.RENDERBUFFER_SAMPLES);
            expect(gl.RENDERBUFFER_SAMPLES).assertEqual(0x8CAB);
            console.info("webgltest gl.FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = ", gl.FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER);
            expect(gl.FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER).assertEqual(0x8CD4);
            console.info("webgltest gl.MAX_COLOR_ATTACHMENTS = ", gl.MAX_COLOR_ATTACHMENTS);
            expect(gl.MAX_COLOR_ATTACHMENTS).assertEqual(0x8CDF);
            console.info("webgltest gl.COLOR_ATTACHMENT1 = ", gl.COLOR_ATTACHMENT1);
            expect(gl.COLOR_ATTACHMENT1).assertEqual(0x8CE1);
            console.info("webgltest gl.COLOR_ATTACHMENT2 = ", gl.COLOR_ATTACHMENT2);
            expect(gl.COLOR_ATTACHMENT2).assertEqual(0x8CE2);
            console.info("webgltest gl.COLOR_ATTACHMENT3 = ", gl.COLOR_ATTACHMENT3);
            expect(gl.COLOR_ATTACHMENT3).assertEqual(0x8CE3);
            console.info("webgltest gl.COLOR_ATTACHMENT4 = ", gl.COLOR_ATTACHMENT4);
            expect(gl.COLOR_ATTACHMENT4).assertEqual(0x8CE4);
            console.info("webgltest gl.COLOR_ATTACHMENT5 = ", gl.COLOR_ATTACHMENT5);
            expect(gl.COLOR_ATTACHMENT5).assertEqual(0x8CE5);
            console.info("webgltest gl.COLOR_ATTACHMENT6 = ", gl.COLOR_ATTACHMENT6);
            expect(gl.COLOR_ATTACHMENT6).assertEqual(0x8CE6);
            console.info("webgltest gl.COLOR_ATTACHMENT7 = ", gl.COLOR_ATTACHMENT7);
            expect(gl.COLOR_ATTACHMENT7).assertEqual(0x8CE7);
            console.info("webgltest gl.COLOR_ATTACHMENT8 = ", gl.COLOR_ATTACHMENT8);
            expect(gl.COLOR_ATTACHMENT8).assertEqual(0x8CE8);
            console.info("webgltest gl.COLOR_ATTACHMENT9 = ", gl.COLOR_ATTACHMENT9);
            expect(gl.COLOR_ATTACHMENT9).assertEqual(0x8CE9);
            console.info("webgltest gl.COLOR_ATTACHMENT10 = ", gl.COLOR_ATTACHMENT10);
            expect(gl.COLOR_ATTACHMENT10).assertEqual(0x8CEA);
            console.info("webgltest gl.COLOR_ATTACHMENT11 = ", gl.COLOR_ATTACHMENT11);
            expect(gl.COLOR_ATTACHMENT11).assertEqual(0x8CEB);
            console.info("webgltest gl.COLOR_ATTACHMENT12 = ", gl.COLOR_ATTACHMENT12);
            expect(gl.COLOR_ATTACHMENT12).assertEqual(0x8CEC);
            console.info("webgltest gl.COLOR_ATTACHMENT13 = ", gl.COLOR_ATTACHMENT13);
            expect(gl.COLOR_ATTACHMENT13).assertEqual(0x8CED);
            console.info("webgltest gl.COLOR_ATTACHMENT14 = ", gl.COLOR_ATTACHMENT14);
            expect(gl.COLOR_ATTACHMENT14).assertEqual(0x8CEE);
            console.info("webgltest gl.COLOR_ATTACHMENT15 = ", gl.COLOR_ATTACHMENT15);
            expect(gl.COLOR_ATTACHMENT15).assertEqual(0x8CEF);
            console.info("webgltest gl.FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = ", gl.FRAMEBUFFER_INCOMPLETE_MULTISAMPLE);
            expect(gl.FRAMEBUFFER_INCOMPLETE_MULTISAMPLE).assertEqual(0x8D56);
            console.info("webgltest gl.MAX_SAMPLES = ", gl.MAX_SAMPLES);
            expect(gl.MAX_SAMPLES).assertEqual(0x8D57);
            console.info("webgltest gl.HALF_FLOAT = ", gl.HALF_FLOAT);
            expect(gl.HALF_FLOAT).assertEqual(0x140B);
            console.info("webgltest gl.RG = ", gl.RG);
            expect(gl.RG).assertEqual(0x8227);
            console.info("webgltest gl.RG_INTEGER = ", gl.RG_INTEGER);
            expect(gl.RG_INTEGER).assertEqual(0x8228);
            console.info("webgltest gl.R8 = ", gl.R8);
            expect(gl.R8).assertEqual(0x8229);
            console.info("webgltest gl.RG8 = ", gl.RG8);
            expect(gl.RG8).assertEqual(0x822B);
            console.info("webgltest gl.R16F = ", gl.R16F);
            expect(gl.R16F).assertEqual(0x822D);
            console.info("webgltest gl.R32F = ", gl.R32F);
            expect(gl.R32F).assertEqual(0x822E);
            console.info("webgltest gl.RG16F = ", gl.RG16F);
            expect(gl.RG16F).assertEqual(0x822F);
            console.info("webgltest gl.RG32F = ", gl.RG32F);
            expect(gl.RG32F).assertEqual(0x8230);
            console.info("webgltest gl.R8I = ", gl.R8I);
            expect(gl.R8I).assertEqual(0x8231);
            console.info("webgltest gl.R8UI = ", gl.R8UI);
            expect(gl.R8UI).assertEqual(0x8232);
            console.info("webgltest gl.R16I = ", gl.R16I);
            expect(gl.R16I).assertEqual(0x8233);
            console.info("webgltest gl.R16UI = ", gl.R16UI);
            expect(gl.R16UI).assertEqual(0x8234);
            console.info("webgltest gl.R32I = ", gl.R32I);
            expect(gl.R32I).assertEqual(0x8235);
            console.info("webgltest gl.R32UI = ", gl.R32UI);
            expect(gl.R32UI).assertEqual(0x8236);
            console.info("webgltest gl.RG8I = ", gl.RG8I);
            expect(gl.RG8I).assertEqual(0x8237);
            console.info("webgltest gl.RG8UI = ", gl.RG8UI);
            expect(gl.RG8UI).assertEqual(0x8238);
            console.info("webgltest gl.RG16I = ", gl.RG16I);
            expect(gl.RG16I).assertEqual(0x8239);
            console.info("webgltest gl.RG16UI = ", gl.RG16UI);
            expect(gl.RG16UI).assertEqual(0x823A);
            console.info("webgltest gl.RG32I = ", gl.RG32I);
            expect(gl.RG32I).assertEqual(0x823B);
            console.info("webgltest gl.RG32UI = ", gl.RG32UI);
            expect(gl.RG32UI).assertEqual(0x823C);
            console.info("webgltest gl.VERTEX_ARRAY_BINDING = ", gl.VERTEX_ARRAY_BINDING);
            expect(gl.VERTEX_ARRAY_BINDING).assertEqual(0x85B5);
            console.info("webgltest gl.R8_SNORM = ", gl.R8_SNORM);
            expect(gl.R8_SNORM).assertEqual(0x8F94);
            console.info("webgltest gl.RG8_SNORM = ", gl.RG8_SNORM);
            expect(gl.RG8_SNORM).assertEqual(0x8F95);
            console.info("webgltest gl.RGB8_SNORM = ", gl.RGB8_SNORM);
            expect(gl.RGB8_SNORM).assertEqual(0x8F96);
            console.info("webgltest gl.RGBA8_SNORM = ", gl.RGBA8_SNORM);
            expect(gl.RGBA8_SNORM).assertEqual(0x8F97);
            console.info("webgltest gl.SIGNED_NORMALIZED = ", gl.SIGNED_NORMALIZED);
            expect(gl.SIGNED_NORMALIZED).assertEqual(0x8F9C);
            console.info("webgltest gl.COPY_READ_BUFFER = ", gl.COPY_READ_BUFFER);
            expect(gl.COPY_READ_BUFFER).assertEqual(0x8F36);
            console.info("webgltest gl.COPY_WRITE_BUFFER = ", gl.COPY_WRITE_BUFFER);
            expect(gl.COPY_WRITE_BUFFER).assertEqual(0x8F37);
            console.info("webgltest gl.COPY_READ_BUFFER_BINDING = ", gl.COPY_READ_BUFFER_BINDING);
            expect(gl.COPY_READ_BUFFER_BINDING).assertEqual(0x8F36); /* Same as COPY_READ_BUFFER */
            console.info("webgltest gl.COPY_WRITE_BUFFER_BINDING = ", gl.COPY_WRITE_BUFFER_BINDING);
            expect(gl.COPY_WRITE_BUFFER_BINDING).assertEqual(0x8F37); /* Same as COPY_WRITE_BUFFER */
            console.info("webgltest gl.UNIFORM_BUFFER = ", gl.UNIFORM_BUFFER);
            expect(gl.UNIFORM_BUFFER).assertEqual(0x8A11);
            console.info("webgltest gl.UNIFORM_BUFFER_BINDING = ", gl.UNIFORM_BUFFER_BINDING);
            expect(gl.UNIFORM_BUFFER_BINDING).assertEqual(0x8A28);
            console.info("webgltest gl.UNIFORM_BUFFER_START = ", gl.UNIFORM_BUFFER_START);
            expect(gl.UNIFORM_BUFFER_START).assertEqual(0x8A29);
            console.info("webgltest gl.UNIFORM_BUFFER_SIZE = ", gl.UNIFORM_BUFFER_SIZE);
            expect(gl.UNIFORM_BUFFER_SIZE).assertEqual(0x8A2A);
            console.info("webgltest gl.MAX_VERTEX_UNIFORM_BLOCKS = ", gl.MAX_VERTEX_UNIFORM_BLOCKS);
            expect(gl.MAX_VERTEX_UNIFORM_BLOCKS).assertEqual(0x8A2B);
            console.info("webgltest gl.MAX_FRAGMENT_UNIFORM_BLOCKS = ", gl.MAX_FRAGMENT_UNIFORM_BLOCKS);
            expect(gl.MAX_FRAGMENT_UNIFORM_BLOCKS).assertEqual(0x8A2D);
            console.info("webgltest gl.MAX_COMBINED_UNIFORM_BLOCKS = ", gl.MAX_COMBINED_UNIFORM_BLOCKS);
            expect(gl.MAX_COMBINED_UNIFORM_BLOCKS).assertEqual(0x8A2E);
            console.info("webgltest gl.MAX_UNIFORM_BUFFER_BINDINGS = ", gl.MAX_UNIFORM_BUFFER_BINDINGS);
            expect(gl.MAX_UNIFORM_BUFFER_BINDINGS).assertEqual(0x8A2F);
            console.info("webgltest gl.MAX_UNIFORM_BLOCK_SIZE = ", gl.MAX_UNIFORM_BLOCK_SIZE);
            expect(gl.MAX_UNIFORM_BLOCK_SIZE).assertEqual(0x8A30);
            console.info("webgltest gl.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = ", gl.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS);
            expect(gl.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS).assertEqual(0x8A31);
            console.info("webgltest gl.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = ", gl.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS);
            expect(gl.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS).assertEqual(0x8A33);
            console.info("webgltest gl.UNIFORM_BUFFER_OFFSET_ALIGNMENT = ", gl.UNIFORM_BUFFER_OFFSET_ALIGNMENT);
            expect(gl.UNIFORM_BUFFER_OFFSET_ALIGNMENT).assertEqual(0x8A34);
            console.info("webgltest gl.ACTIVE_UNIFORM_BLOCKS = ", gl.ACTIVE_UNIFORM_BLOCKS);
            expect(gl.ACTIVE_UNIFORM_BLOCKS).assertEqual(0x8A36);
            console.info("webgltest gl.UNIFORM_TYPE = ", gl.UNIFORM_TYPE);
            expect(gl.UNIFORM_TYPE).assertEqual(0x8A37);
            console.info("webgltest gl.UNIFORM_SIZE = ", gl.UNIFORM_SIZE);
            expect(gl.UNIFORM_SIZE).assertEqual(0x8A38);
            console.info("webgltest gl.UNIFORM_BLOCK_INDEX = ", gl.UNIFORM_BLOCK_INDEX);
            expect(gl.UNIFORM_BLOCK_INDEX).assertEqual(0x8A3A);
            console.info("webgltest gl.UNIFORM_OFFSET = ", gl.UNIFORM_OFFSET);
            expect(gl.UNIFORM_OFFSET).assertEqual(0x8A3B);
            console.info("webgltest gl.UNIFORM_ARRAY_STRIDE = ", gl.UNIFORM_ARRAY_STRIDE);
            expect(gl.UNIFORM_ARRAY_STRIDE).assertEqual(0x8A3C);
            console.info("webgltest gl.UNIFORM_MATRIX_STRIDE = ", gl.UNIFORM_MATRIX_STRIDE);
            expect(gl.UNIFORM_MATRIX_STRIDE).assertEqual(0x8A3D);
            console.info("webgltest gl.UNIFORM_IS_ROW_MAJOR = ", gl.UNIFORM_IS_ROW_MAJOR);
            expect(gl.UNIFORM_IS_ROW_MAJOR).assertEqual(0x8A3E);
            console.info("webgltest gl.UNIFORM_BLOCK_BINDING = ", gl.UNIFORM_BLOCK_BINDING);
            expect(gl.UNIFORM_BLOCK_BINDING).assertEqual(0x8A3F);
            console.info("webgltest gl.UNIFORM_BLOCK_DATA_SIZE = ", gl.UNIFORM_BLOCK_DATA_SIZE);
            expect(gl.UNIFORM_BLOCK_DATA_SIZE).assertEqual(0x8A40);
            console.info("webgltest gl.UNIFORM_BLOCK_ACTIVE_UNIFORMS = ", gl.UNIFORM_BLOCK_ACTIVE_UNIFORMS);
            expect(gl.UNIFORM_BLOCK_ACTIVE_UNIFORMS).assertEqual(0x8A42);
            console.info("webgltest gl.UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = ", gl.UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES);
            expect(gl.UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES).assertEqual(0x8A43);
            console.info("webgltest gl.UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = ", gl.UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER);
            expect(gl.UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER).assertEqual(0x8A44);
            console.info("webgltest gl.UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = ", gl.UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER);
            expect(gl.UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER).assertEqual(0x8A46);
            console.info("webgltest gl.INVALID_INDEX = ", gl.INVALID_INDEX);
            expect(gl.INVALID_INDEX).assertEqual(0xFFFFFFFF);
            console.info("webgltest gl.MAX_VERTEX_OUTPUT_COMPONENTS = ", gl.MAX_VERTEX_OUTPUT_COMPONENTS);
            expect(gl.MAX_VERTEX_OUTPUT_COMPONENTS).assertEqual(0x9122);
            console.info("webgltest gl.MAX_FRAGMENT_INPUT_COMPONENTS = ", gl.MAX_FRAGMENT_INPUT_COMPONENTS);
            expect(gl.MAX_FRAGMENT_INPUT_COMPONENTS).assertEqual(0x9125);
            console.info("webgltest gl.MAX_SERVER_WAIT_TIMEOUT = ", gl.MAX_SERVER_WAIT_TIMEOUT);
            expect(gl.MAX_SERVER_WAIT_TIMEOUT).assertEqual(0x9111);
            console.info("webgltest gl.OBJECT_TYPE = ", gl.OBJECT_TYPE);
            expect(gl.OBJECT_TYPE).assertEqual(0x9112);
            console.info("webgltest gl.SYNC_CONDITION = ", gl.SYNC_CONDITION);
            expect(gl.SYNC_CONDITION).assertEqual(0x9113);
            console.info("webgltest gl.SYNC_STATUS = ", gl.SYNC_STATUS);
            expect(gl.SYNC_STATUS).assertEqual(0x9114);
            console.info("webgltest gl.SYNC_FLAGS = ", gl.SYNC_FLAGS);
            expect(gl.SYNC_FLAGS).assertEqual(0x9115);
            console.info("webgltest gl.SYNC_FENCE = ", gl.SYNC_FENCE);
            expect(gl.SYNC_FENCE).assertEqual(0x9116);
            console.info("webgltest gl.SYNC_GPU_COMMANDS_COMPLETE = ", gl.SYNC_GPU_COMMANDS_COMPLETE);
            expect(gl.SYNC_GPU_COMMANDS_COMPLETE).assertEqual(0x9117);
            console.info("webgltest gl.UNSIGNALED = ", gl.UNSIGNALED);
            expect(gl.UNSIGNALED).assertEqual(0x9118);
            console.info("webgltest gl.SIGNALED = ", gl.SIGNALED);
            expect(gl.SIGNALED).assertEqual(0x9119);
            console.info("webgltest gl.ALREADY_SIGNALED = ", gl.ALREADY_SIGNALED);
            expect(gl.ALREADY_SIGNALED).assertEqual(0x911A);
            console.info("webgltest gl.TIMEOUT_EXPIRED = ", gl.TIMEOUT_EXPIRED);
            expect(gl.TIMEOUT_EXPIRED).assertEqual(0x911B);
            console.info("webgltest gl.CONDITION_SATISFIED = ", gl.CONDITION_SATISFIED);
            expect(gl.CONDITION_SATISFIED).assertEqual(0x911C);
            console.info("webgltest gl.WAIT_FAILED = ", gl.WAIT_FAILED);
            expect(gl.WAIT_FAILED).assertEqual(0x911D);
            console.info("webgltest gl.SYNC_FLUSH_COMMANDS_BIT = ", gl.SYNC_FLUSH_COMMANDS_BIT);
            expect(gl.SYNC_FLUSH_COMMANDS_BIT).assertEqual(0x00000001);
            console.info("webgltest gl.VERTEX_ATTRIB_ARRAY_DIVISOR = ", gl.VERTEX_ATTRIB_ARRAY_DIVISOR);
            expect(gl.VERTEX_ATTRIB_ARRAY_DIVISOR).assertEqual(0x88FE);
            console.info("webgltest gl.ANY_SAMPLES_PASSED = ", gl.ANY_SAMPLES_PASSED);
            expect(gl.ANY_SAMPLES_PASSED).assertEqual(0x8C2F);
            console.info("webgltest gl.ANY_SAMPLES_PASSED_CONSERVATIVE = ", gl.ANY_SAMPLES_PASSED_CONSERVATIVE);
            expect(gl.ANY_SAMPLES_PASSED_CONSERVATIVE).assertEqual(0x8D6A);
            console.info("webgltest gl.SAMPLER_BINDING = ", gl.SAMPLER_BINDING);
            expect(gl.SAMPLER_BINDING).assertEqual(0x8919);
            console.info("webgltest gl.RGB10_A2UI = ", gl.RGB10_A2UI);
            expect(gl.RGB10_A2UI).assertEqual(0x906F);
            console.info("webgltest gl.INT_2_10_10_10_REV = ", gl.INT_2_10_10_10_REV);
            expect(gl.INT_2_10_10_10_REV).assertEqual(0x8D9F);
            console.info("webgltest gl.TRANSFORM_FEEDBACK = ", gl.TRANSFORM_FEEDBACK);
            expect(gl.TRANSFORM_FEEDBACK).assertEqual(0x8E22);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_PAUSED = ", gl.TRANSFORM_FEEDBACK_PAUSED);
            expect(gl.TRANSFORM_FEEDBACK_PAUSED).assertEqual(0x8E23);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_ACTIVE = ", gl.TRANSFORM_FEEDBACK_ACTIVE);
            expect(gl.TRANSFORM_FEEDBACK_ACTIVE).assertEqual(0x8E24);
            console.info("webgltest gl.TRANSFORM_FEEDBACK_BINDING = ", gl.TRANSFORM_FEEDBACK_BINDING);
            expect(gl.TRANSFORM_FEEDBACK_BINDING).assertEqual(0x8E25);
            console.info("webgltest gl.TEXTURE_IMMUTABLE_FORMAT = ", gl.TEXTURE_IMMUTABLE_FORMAT);
            expect(gl.TEXTURE_IMMUTABLE_FORMAT).assertEqual(0x912F);
            console.info("webgltest gl.MAX_ELEMENT_INDEX = ", gl.MAX_ELEMENT_INDEX);
            expect(gl.MAX_ELEMENT_INDEX).assertEqual(0x8D6B);
            console.info("webgltest gl.TEXTURE_IMMUTABLE_LEVELS = ", gl.TEXTURE_IMMUTABLE_LEVELS);
            expect(gl.TEXTURE_IMMUTABLE_LEVELS).assertEqual(0x82DF);
            console.info("webgltest gl.TIMEOUT_IGNORED = ", gl.TIMEOUT_IGNORED);
            expect(gl.TIMEOUT_IGNORED).assertEqual(-1);
            /* WebGL-specific enums */
            console.info("webgltest gl.MAX_CLIENT_WAIT_TIMEOUT_WEBGL = ", gl.MAX_CLIENT_WAIT_TIMEOUT_WEBGL);
            expect(gl.MAX_CLIENT_WAIT_TIMEOUT_WEBGL).assertEqual(0x9247);
            done();
        });
    })
}
