/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { describe, it, expect, TestType, Size, Level, beforeAll } from "../../../hypium/index";
import hilog from '@ohos.hilog'
import { BusinessError } from '@ohos.base';
import common from '@ohos.app.ability.common';
import UIAbility from '@ohos.app.ability.UIAbility';
import text from "@ohos.graphics.text"
import image from '@ohos.multimedia.image';
import type drawing from '@ohos.graphics.drawing';
import type common2D from '@ohos.graphics.common2D';
import Utils from './Util.test';

let domain: number = 0x0000; //日志标识,0x0000作为测试框架的业务标识
let tag: string = 'testTag'; //日志标识字符串,作为tag标识当前runner类下的测试行为

export default function ParagraphTest() {
  describe("ParagraphTest", (): void => {
    let globalFontCollection: text.FontCollection;
    let globalTextStyle: text.TextStyle;
    let globalParagraphStyle: text.ParagraphStyle;
    let globalStructStyle: text.StrutStyle;
    let globalCanvas: drawing.Canvas;
    let checkFontStyle: text.FontStyle;

    beforeAll(() => {
      hilog.info(domain, tag, '%{public}s', 'beforeEach start');
      try {
        globalFontCollection = text.FontCollection.getGlobalInstance()
        globalFontCollection.loadFontSync('myFamilyName', 'file:///system/fonts/HarmonyOS_Sans.ttf')
        let myFontFamily: Array<string> = ["myFamilyName"]
        let myColor: common2D.Color = { alpha: 255, red: 255, green: 0, blue: 0 };

        let fontFeatures: Array<text.FontFeature> = new Array<text.FontFeature>(2);
        fontFeatures[0] = { name: "liga", value: 1 };
        fontFeatures[1] = { name: "liga2", value: 2 };
        let fontVariation: Array<text.FontVariation> = new Array<text.FontVariation>(2);
        fontVariation[0] = { axis: "axis", value: 1 };
        fontVariation[1] = { axis: "axis2", value: 2 };
        let textShadows: Array<text.TextShadow> = new Array<text.TextShadow>(2);
        let point1: common2D.Point = { x: 11, y: 12 };
        let point2: common2D.Point = { x: 2, y: 4 };
        textShadows[0] = {
          color: myColor,
          point: point1, blurRadius: 12
        };
        textShadows[1] = {
          color: myColor,
          point: point2, blurRadius: 14
        };
        let backgroundRect: text.RectStyle = {
          color: myColor,
          leftTopRadius: 10,
          rightTopRadius: 20,
          rightBottomRadius: 30,
          leftBottomRadius: 40
        };
        let decoration: text.Decoration = {
          color: myColor,
          textDecoration: text.TextDecorationType.UNDERLINE,
          decorationStyle: text.TextDecorationStyle.DOTTED,
          decorationThicknessScale: 12
        }

        globalTextStyle = {
          decoration: decoration,
          color: myColor,
          fontWeight: text.FontWeight.W700,
          fontStyle: text.FontStyle.OBLIQUE,
          baseline: text.TextBaseline.ALPHABETIC,
          fontFamilies: myFontFamily,
          fontSize: 32,
          letterSpacing: 33,
          wordSpacing: 24,
          heightScale: 13,
          halfLeading: false,
          heightOnly: true,
          ellipsis: "...",
          ellipsisMode: text.EllipsisMode.END,
          locale: "zh-cn",
          baselineShift: 13,
          fontFeatures: fontFeatures,
          textShadows: textShadows,
          fontVariations: fontVariation,
          backgroundRect: backgroundRect,
        };
        checkFontStyle = globalTextStyle?.fontStyle ?? text.FontStyle.NORMAL;
        if (checkFontStyle == text.FontStyle.OBLIQUE) {
          checkFontStyle = text.FontStyle.ITALIC
        }

        globalStructStyle = {
          fontStyle: text.FontStyle.OBLIQUE,
          fontWidth: text.FontWidth.SEMI_CONDENSED,
          fontWeight: text.FontWeight.W400,
          fontSize: 12,
          height: 15,
          leading: 2,
          forceHeight: true,
          enabled: false,
          heightOverride: true,
          halfLeading: false,
        }

        let textTab: text.TextTab = { alignment: text.TextAlign.START, location: 512 }

        globalParagraphStyle = {
          textStyle: globalTextStyle,
          textDirection: text.TextDirection.RTL,
          align: text.TextAlign.JUSTIFY,
          wordBreak: text.WordBreak.BREAK_ALL,
          maxLines: 10,
          breakStrategy: text.BreakStrategy.BALANCED,
          strutStyle: globalStructStyle,
          textHeightBehavior: text.TextHeightBehavior.DISABLE_LAST_ASCENT,
          tab: textTab
        };

        // const opts: image.InitializationOptions = {
        //   size: { width: 480, height: 360 },
        //   editable: true,
        //   pixelFormat: image.PixelMapFormat.BGRA_8888,
        // };
        // let pixelMap: image.PixelMap = image.createPixelMapSync(opts);
        // if (pixelMap == undefined) {
        //   hilog.error(domain, tag, `Create image.createPixelMapSync failed`);
        //   return;
        // }
        // globalCanvas = new drawing.Canvas(pixelMap)
      } catch (err) {
        hilog.error(domain, tag, `Failed in ParagraphTest init global params. Cause:${JSON.stringify(err)}`);
      }
    })

    /**
     * @tc.number    : testCreateParagraphStatic
     * @tc.name      : testCreateParagraphStatic
     * @tc.desc      : To test create a paragraph.
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : LEVEL1
     */
    it('testCreateParagraphStatic', TestType.FUNCTION | Size.MEDIUMTEST | Level.LEVEL1,
      async (done: () => void): Promise<void> => {
        try {
          let paragraphBuilder = new text.ParagraphBuilder(globalParagraphStyle, globalFontCollection)
          // let paragraphBuilder = new text.ParagraphBuilder()
          expect(paragraphBuilder !== undefined).assertTrue()
          paragraphBuilder.pushStyle(globalTextStyle);
          paragraphBuilder.addText("Hello World!");
          let paragraph = paragraphBuilder.build();
          expect(paragraph !== undefined).assertTrue()
          done()
        } catch (err) {
          hilog.error(domain, tag, `Failed in create a paragraph. Cause:${JSON.stringify(err)}`);
          expect().assertFail();
          done()
        }
      })

    /**
     * @tc.number    : testGetLineMetricsAtStatic
     * @tc.name      : testGetLineMetricsAtStatic
     * @tc.desc      : To test method getLineMetricsAt for paragraph.
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : LEVEL1
     */
    it('testGetLineMetricsAtStatic', TestType.FUNCTION | Size.MEDIUMTEST | Level.LEVEL1,
      async (done: () => void): Promise<void> => {
        try {
          hilog.error(0x0000, 'Text', 'MM_LOG print maxLines: %{public}f', globalParagraphStyle.maxLines);
          let paragraphBuilder = new text.ParagraphBuilder(globalParagraphStyle, globalFontCollection)
          expect(paragraphBuilder !== undefined).assertTrue()
          paragraphBuilder.pushStyle(globalTextStyle);
          paragraphBuilder.addText("The quick brown fox jumps over the lazy dog.");
          let paragraph = paragraphBuilder.build();
          expect(paragraph !== undefined).assertTrue()
          paragraph.layoutSync(100);
          let lineMetrics: text.LineMetrics | undefined = paragraph.getLineMetrics(2);
          if (lineMetrics !== undefined) {
            hilog.error(0x0000, 'Text', 'MM_LOG one line metrics info data: %{public}s', JSON.stringify(lineMetrics));
            expect(Math.round(Number(lineMetrics?.ascent ?? 0) * 100) / 100).assertEqual(303.39)
            expect(Math.round(Number(lineMetrics?.descent ?? 0) * 100) / 100).assertEqual(112.61)
            expect(lineMetrics?.height).assertEqual(416)
            expect(Math.round(Number(lineMetrics?.width ?? 0) * 100) / 100).assertEqual(50.50)
            expect(Math.round(Number(lineMetrics?.left ?? 0) * 100) / 100).assertEqual(49.50)
            expect(Math.round(Number(lineMetrics?.baseline ?? 0) * 100) / 100).assertEqual(1135.39)
            expect(lineMetrics?.lineNumber).assertEqual(2)
            expect(lineMetrics?.topHeight).assertEqual(832)

            let runMetrics: Map<number, text.RunMetrics> | undefined = lineMetrics?.runMetrics;
            if (runMetrics != undefined) {
              runMetrics.forEach((value, key) => {
                let textStyle: text.TextStyle = value.textStyle;
                let fontMetrics: drawing.FontMetrics = value.fontMetrics;
                hilog.error(0x0000, 'Text', 'MM_LOG run metrics textStyle data: %{public}s', JSON.stringify(textStyle));
                hilog.error(0x0000, 'Text', 'MM_LOG run metrics fontMetrics data: %{public}s',
                  JSON.stringify(fontMetrics));

                if (textStyle.decoration && globalTextStyle.decoration) {
                  expect(textStyle.decoration?.textDecoration).assertEqual(globalTextStyle.decoration?.textDecoration)
                  expect(textStyle.decoration?.decorationStyle).assertEqual(globalTextStyle.decoration?.decorationStyle)
                }
                expect(textStyle.fontWeight).assertEqual(globalTextStyle.fontWeight)
                expect(textStyle.fontStyle).assertEqual(checkFontStyle)
                expect(textStyle.baseline).assertEqual(globalTextStyle.baseline)
                expect(textStyle.fontFamilies?.length ?? 0).assertEqual(2)
                expect(textStyle.fontSize).assertEqual(globalTextStyle.fontSize)
                expect(textStyle.letterSpacing).assertEqual(globalTextStyle.letterSpacing)
                expect(textStyle.wordSpacing).assertEqual(globalTextStyle.wordSpacing)
                expect(textStyle.heightScale).assertEqual(globalTextStyle.heightScale)
                expect(textStyle.halfLeading).assertEqual(globalTextStyle.halfLeading)
                expect(textStyle.ellipsis).assertEqual("")
                expect(textStyle.ellipsisMode).assertEqual(globalTextStyle.ellipsisMode)
                expect(textStyle.locale).assertEqual(globalTextStyle.locale)
                expect(textStyle.baselineShift).assertEqual(globalTextStyle.baselineShift)
                expect(textStyle.fontFeatures?.length?? 0).assertEqual(globalTextStyle.fontFeatures?.length?? 0)
                expect(textStyle.textShadows?.length?? 0).assertEqual(globalTextStyle.textShadows?.length?? 0)
                if (textStyle.backgroundRect && globalTextStyle.backgroundRect) {
                  expect(textStyle.backgroundRect?.leftTopRadius).assertEqual(globalTextStyle.backgroundRect?.leftTopRadius)
                  expect(textStyle.backgroundRect?.rightTopRadius).assertEqual(globalTextStyle.backgroundRect?.rightTopRadius)
                  expect(textStyle.backgroundRect?.rightBottomRadius).assertEqual(globalTextStyle.backgroundRect?.rightBottomRadius)
                  expect(textStyle.backgroundRect?.leftBottomRadius).assertEqual(globalTextStyle.backgroundRect?.leftBottomRadius)
                }
                expect(Math.round(fontMetrics.ascent * 100) / 100).assertEqual(-29.70)
                expect(Math.round(fontMetrics.descent * 100) / 100).assertEqual(7.81)
                expect(Math.round(fontMetrics.top * 100) / 100).assertEqual(-33.79)
                expect(Math.round(fontMetrics.bottom * 100) / 100).assertEqual(8.67)
                expect(Math.round(fontMetrics.leading * 100) / 100).assertEqual(0)
              })
            }
          }

          done()
        } catch (err) {
          hilog.error(domain, tag, `Failed in getLineMetricsAt. Cause:${JSON.stringify(err)}`);
          expect().assertFail();
          done()
        }
      })

    /**
     * @tc.number    : testPaintStatic
     * @tc.name      : testPaintStatic
     * @tc.desc      : To test method paint for paragraph.
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : LEVEL1
     */
    it('testPaintStatic', TestType.FUNCTION | Size.MEDIUMTEST | Level.LEVEL1,
      async (done: () => void): Promise<void> => {
        try {
          hilog.error(0x0000, 'Text', 'MM_LOG print maxLines: %{public}f', globalParagraphStyle.maxLines);
          let paragraphBuilder = new text.ParagraphBuilder(globalParagraphStyle, globalFontCollection)
          expect(paragraphBuilder !== undefined).assertTrue()
          paragraphBuilder.pushStyle(globalTextStyle);
          paragraphBuilder.addText("The quick brown fox jumps over the lazy dog.");
          let paragraph = paragraphBuilder.build();
          expect(paragraph !== undefined).assertTrue()
          paragraph.layoutSync(100);
          expect(true).assertTrue();
          done()
        } catch (err) {
          hilog.error(domain, tag, `Failed in getLineMetricsAt. Cause:${JSON.stringify(err)}`);
          expect().assertFail();
          done()
        }
      })

    /**
     * @tc.number    : testPaintOnPathStatic_01
     * @tc.name      : testPaintOnPathStatic_01
     * @tc.desc      : To test method paintOnPath for paragraph.
     * @tc.size      : MediumTest
     * @tc.type      : Function
     * @tc.level     : LEVEL1
     */
    it('testPaintOnPathStatic_01', TestType.FUNCTION | Size.MEDIUMTEST | Level.LEVEL1,
      async (done: () => void): Promise<void> => {
        try {
          hilog.error(0x0000, 'Text', 'MM_LOG print maxLines: %{public}f', globalParagraphStyle.maxLines);
          let paragraphBuilder = new text.ParagraphBuilder(globalParagraphStyle, globalFontCollection)
          expect(paragraphBuilder !== undefined).assertTrue()
          console.info('www data text ', 1111)
          paragraphBuilder.pushStyle(globalTextStyle);
          console.info('www data text ', 2222)
          paragraphBuilder.addText("The quick brown fox jumps over the lazy dog.");
          console.info('www data text ', 3333)
          let paragraph = paragraphBuilder.build();
          console.info('www data text ', 4444)
          expect(paragraph !== undefined).assertTrue()
          paragraph.layoutSync(100);
          console.info('www data text ', 5555)
          expect(true).assertTrue();
          done()
        } catch (err) {
          hilog.error(domain, tag, `Failed in getLineMetricsAt. Cause:${JSON.stringify(err)}`);
          expect().assertFail();
          done()
        }
      })
  })

}