/**
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { describe, beforeAll, beforeEach, afterEach, afterAll, it, expect, Level } from "../../../../hypium/index"
import router from '@ohos.router';
import { Driver, ON, loadAndSetUpUiTest} from '@ohos.UiTest';
import CommonFunc from '../../../ets/MainAbility/common/Common';
import inspector from '@ohos.arkui.inspector'
import hilog from '@ohos.hilog'
import abilityDelegatorRegistry from '@ohos.app.ability.abilityDelegatorRegistry';
import UIAbility from '@ohos.app.ability.UIAbility';
import common from '@ohos.app.ability.common';
import { BusinessError } from '@ohos.base';
import { UIContext, Router } from '@ohos.arkui.UIContext';
import { AppStorage } from '@ohos.arkui.stateManagement';
import { UtilsTest } from '../Util.test';
let domain: number = 0x0000;
let tag: string = 'testTag';
let testAbilityContext:common.UIAbilityContext;
export default function text_drag() {
  describe('text_drag', () :void=> {
    beforeAll(() => {
      console.info("text_drag beforeEach start");
      await UtilsTest.loadAndSetUpUiTest();
      await UtilsTest.msSleep(4000)
      await UtilsTest.startAbility("com.arkui.ace.imageText.nowear.static", "EntryAbility")
      await UtilsTest.msSleep(4000)
    });

    beforeEach(async (): Promise<void> => {
      console.info("text_drag beforeEach start");
      let options: router.RouterOptions = {
        url: "MainAbility/pages/text/TextDrag",
      }
      try {
        const routerInstance = AppStorage.get<Router>("router", Type.from<Router>()) as Router
        routerInstance.clear();
        let pages = routerInstance.getState();
        console.info("get text_drag state pages:" + "");
        if (!("TextClockApi" == pages.name)) {
          console.info("get text_drag pages.name:" + "");
          // await router 有已知问题，先注释,使用 routerInstance.pushUrl(options);
          // let result = await routerInstance.pushUrl(options);
          routerInstance.pushUrl(options);
          await CommonFunc.sleep(2000);
          // console.info("push text_drag page result:" + JSON.stringify(result));
        }
      } catch (err) {
        console.error("push text_drag page error:" + err);
      }
      console.info("text_drag beforeEach end");
    });
    afterEach(async () => {
      await CommonFunc.sleep(1000);
      console.info("text_drag after each called");
    });
    afterEach(async () => {
      await CommonFunc.sleep(1000);
      console.info("positionSetting after each called");
    });
    
    /* *
       * @tc.number: SUB_ACE_UI_TEXT_DRAG_0100
       * @tc.name  : text_drag_001
       * @tc.desc  : After longClick on Text Component, drag text and check text state
       * @tc.level : Level 1
       * @tc.type : Function
       * @tc.size : MediumTest
       */
    it('SUB_ACE_UI_TEXT_DRAG_static_0100', Level.LEVEL1, async (done: ()=>void) => {

      console.info('[text_drag_001] START');
      let driver = Driver.create();
      let textComponent = await driver.findComponent(ON.id('DraggedText'));
      //first step: longClick
      await (textComponent?.longClick() as Promise<void>);
      await CommonFunc.sleep(500);
      console.info('[text_drag_001] longClick success');
      let selectAllButton = await driver.findComponent(ON.text('全选'));
      selectAllButton?.click();
      await CommonFunc.sleep(300);
      let strJson1 = inspector.getInspectorByKey('DraggedText');
      console.info(`[text_drag_001] DraggedText strJson1 is:${strJson1}`);
      let obj1 = JSON.parseJsonElement(strJson1);
      console.info(`[text_drag_001] DraggedText selection range is:${obj1.getElement('$attrs').getString('selection')}`);
      await CommonFunc.sleep(300);
      expect(obj1.getElement('$attrs').getString('selection')).assertEqual('[0,45]');

      //second step: drag text to textArea
      let textAreaComponent = await driver.findComponent(ON.id('textAreaDrag'));
      textComponent?.dragTo(textAreaComponent!);
      let strJson2 = inspector.getInspectorByKey('DraggedText');
      console.info(`[text_drag_001] DraggedText strJson2 is:${strJson2}`);
      let obj2 = JSON.parseJsonElement(strJson2);
      console.info(`[text_drag_001] after dragging text, selection range is:${obj2.getElement('$attrs').getString('selection')}`);
      await CommonFunc.sleep(300);
      expect(obj2.getElement('$attrs').getString('selection')).assertEqual('[-1,-1]');
      let textAreaContent = textAreaComponent?.getText() ;
      expect(textAreaContent).assertEqual('test drag event draggable设为true, 有onDragStart');

      console.info('[text_drag_001] END');
      done();
    });
    
  })
}