/*
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <climits>
#include <gtest/gtest.h>
#include "../ImageBaseFunc.h"
#include "../ActsImage0017TestSuite.h"
#include "shrinkdefine.h"

using namespace std;
using namespace testing::ext;
using namespace OHOS;

static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8unorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8snorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8uscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8sscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8uint, "dEQP-VK.image.extended_usage_bit.attachment_read.r8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8sint, "dEQP-VK.image.extended_usage_bit.attachment_read.r8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8unorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8snorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8uscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8sscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8uint, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8sint, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16unorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16snorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16uscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16sscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16uint, "dEQP-VK.image.extended_usage_bit.attachment_read.r16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16sint, "dEQP-VK.image.extended_usage_bit.attachment_read.r16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16sfloat, "dEQP-VK.image.extended_usage_bit.attachment_read.r16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8b8a8unorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8b8a8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8b8a8snorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8b8a8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8b8a8uscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8b8a8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8b8a8sscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8b8a8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8b8a8uint, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8b8a8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR8g8b8a8sint, "dEQP-VK.image.extended_usage_bit.attachment_read.r8g8b8a8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadA8b8g8r8unormpack32, "dEQP-VK.image.extended_usage_bit.attachment_read.a8b8g8r8_unorm_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadA8b8g8r8snormpack32, "dEQP-VK.image.extended_usage_bit.attachment_read.a8b8g8r8_snorm_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadA8b8g8r8uscaledpack32, "dEQP-VK.image.extended_usage_bit.attachment_read.a8b8g8r8_uscaled_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadA8b8g8r8sscaledpack32, "dEQP-VK.image.extended_usage_bit.attachment_read.a8b8g8r8_sscaled_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadA8b8g8r8uintpack32, "dEQP-VK.image.extended_usage_bit.attachment_read.a8b8g8r8_uint_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadA8b8g8r8sintpack32, "dEQP-VK.image.extended_usage_bit.attachment_read.a8b8g8r8_sint_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16unorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16snorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16uscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16sscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16uint, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16sint, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16sfloat, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR32uint, "dEQP-VK.image.extended_usage_bit.attachment_read.r32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR32sint, "dEQP-VK.image.extended_usage_bit.attachment_read.r32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR32sfloat, "dEQP-VK.image.extended_usage_bit.attachment_read.r32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16b16a16unorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16b16a16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16b16a16snorm, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16b16a16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16b16a16uscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16b16a16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16b16a16sscaled, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16b16a16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16b16a16uint, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16b16a16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16b16a16sint, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16b16a16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR16g16b16a16sfloat, "dEQP-VK.image.extended_usage_bit.attachment_read.r16g16b16a16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR32g32uint, "dEQP-VK.image.extended_usage_bit.attachment_read.r32g32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR32g32sint, "dEQP-VK.image.extended_usage_bit.attachment_read.r32g32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR32g32sfloat, "dEQP-VK.image.extended_usage_bit.attachment_read.r32g32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR32g32b32a32uint, "dEQP-VK.image.extended_usage_bit.attachment_read.r32g32b32a32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR32g32b32a32sint, "dEQP-VK.image.extended_usage_bit.attachment_read.r32g32b32a32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentreadR32g32b32a32sfloat, "dEQP-VK.image.extended_usage_bit.attachment_read.r32g32b32a32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8unorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8snorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8uscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8sscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8uint, "dEQP-VK.image.extended_usage_bit.attachment_write.r8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8sint, "dEQP-VK.image.extended_usage_bit.attachment_write.r8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8unorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8snorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8uscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8sscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8uint, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8sint, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16unorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16snorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16uscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16sscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16uint, "dEQP-VK.image.extended_usage_bit.attachment_write.r16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16sint, "dEQP-VK.image.extended_usage_bit.attachment_write.r16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16sfloat, "dEQP-VK.image.extended_usage_bit.attachment_write.r16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8b8a8unorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8b8a8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8b8a8snorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8b8a8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8b8a8uscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8b8a8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8b8a8sscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8b8a8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8b8a8uint, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8b8a8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR8g8b8a8sint, "dEQP-VK.image.extended_usage_bit.attachment_write.r8g8b8a8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteA8b8g8r8unormpack32, "dEQP-VK.image.extended_usage_bit.attachment_write.a8b8g8r8_unorm_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteA8b8g8r8snormpack32, "dEQP-VK.image.extended_usage_bit.attachment_write.a8b8g8r8_snorm_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteA8b8g8r8uscaledpack32, "dEQP-VK.image.extended_usage_bit.attachment_write.a8b8g8r8_uscaled_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteA8b8g8r8sscaledpack32, "dEQP-VK.image.extended_usage_bit.attachment_write.a8b8g8r8_sscaled_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteA8b8g8r8uintpack32, "dEQP-VK.image.extended_usage_bit.attachment_write.a8b8g8r8_uint_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteA8b8g8r8sintpack32, "dEQP-VK.image.extended_usage_bit.attachment_write.a8b8g8r8_sint_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16unorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16snorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16uscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16sscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16uint, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16sint, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16sfloat, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR32uint, "dEQP-VK.image.extended_usage_bit.attachment_write.r32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR32sint, "dEQP-VK.image.extended_usage_bit.attachment_write.r32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR32sfloat, "dEQP-VK.image.extended_usage_bit.attachment_write.r32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16b16a16unorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16b16a16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16b16a16snorm, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16b16a16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16b16a16uscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16b16a16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16b16a16sscaled, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16b16a16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16b16a16uint, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16b16a16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16b16a16sint, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16b16a16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR16g16b16a16sfloat, "dEQP-VK.image.extended_usage_bit.attachment_write.r16g16b16a16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR32g32uint, "dEQP-VK.image.extended_usage_bit.attachment_write.r32g32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR32g32sint, "dEQP-VK.image.extended_usage_bit.attachment_write.r32g32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR32g32sfloat, "dEQP-VK.image.extended_usage_bit.attachment_write.r32g32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR32g32b32a32uint, "dEQP-VK.image.extended_usage_bit.attachment_write.r32g32b32a32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR32g32b32a32sint, "dEQP-VK.image.extended_usage_bit.attachment_write.r32g32b32a32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCAttachmentwriteR32g32b32a32sfloat, "dEQP-VK.image.extended_usage_bit.attachment_write.r32g32b32a32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8unorm, "dEQP-VK.image.extended_usage_bit.texture_read.r8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8snorm, "dEQP-VK.image.extended_usage_bit.texture_read.r8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8uscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8sscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8uint, "dEQP-VK.image.extended_usage_bit.texture_read.r8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8sint, "dEQP-VK.image.extended_usage_bit.texture_read.r8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8unorm, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8snorm, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8uscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8sscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8uint, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8sint, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16unorm, "dEQP-VK.image.extended_usage_bit.texture_read.r16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16snorm, "dEQP-VK.image.extended_usage_bit.texture_read.r16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16uscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16sscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16uint, "dEQP-VK.image.extended_usage_bit.texture_read.r16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16sint, "dEQP-VK.image.extended_usage_bit.texture_read.r16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16sfloat, "dEQP-VK.image.extended_usage_bit.texture_read.r16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8b8a8unorm, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8b8a8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8b8a8snorm, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8b8a8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8b8a8uscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8b8a8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8b8a8sscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8b8a8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8b8a8uint, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8b8a8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR8g8b8a8sint, "dEQP-VK.image.extended_usage_bit.texture_read.r8g8b8a8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadA8b8g8r8unormpack32, "dEQP-VK.image.extended_usage_bit.texture_read.a8b8g8r8_unorm_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadA8b8g8r8snormpack32, "dEQP-VK.image.extended_usage_bit.texture_read.a8b8g8r8_snorm_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadA8b8g8r8uscaledpack32, "dEQP-VK.image.extended_usage_bit.texture_read.a8b8g8r8_uscaled_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadA8b8g8r8sscaledpack32, "dEQP-VK.image.extended_usage_bit.texture_read.a8b8g8r8_sscaled_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadA8b8g8r8uintpack32, "dEQP-VK.image.extended_usage_bit.texture_read.a8b8g8r8_uint_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadA8b8g8r8sintpack32, "dEQP-VK.image.extended_usage_bit.texture_read.a8b8g8r8_sint_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16unorm, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16snorm, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16uscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16sscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16uint, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16sint, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16sfloat, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR32uint, "dEQP-VK.image.extended_usage_bit.texture_read.r32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR32sint, "dEQP-VK.image.extended_usage_bit.texture_read.r32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR32sfloat, "dEQP-VK.image.extended_usage_bit.texture_read.r32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16b16a16unorm, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16b16a16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16b16a16snorm, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16b16a16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16b16a16uscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16b16a16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16b16a16sscaled, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16b16a16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16b16a16uint, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16b16a16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16b16a16sint, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16b16a16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR16g16b16a16sfloat, "dEQP-VK.image.extended_usage_bit.texture_read.r16g16b16a16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR32g32uint, "dEQP-VK.image.extended_usage_bit.texture_read.r32g32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR32g32sint, "dEQP-VK.image.extended_usage_bit.texture_read.r32g32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR32g32sfloat, "dEQP-VK.image.extended_usage_bit.texture_read.r32g32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR32g32b32a32uint, "dEQP-VK.image.extended_usage_bit.texture_read.r32g32b32a32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR32g32b32a32sint, "dEQP-VK.image.extended_usage_bit.texture_read.r32g32b32a32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturereadR32g32b32a32sfloat, "dEQP-VK.image.extended_usage_bit.texture_read.r32g32b32a32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8unorm, "dEQP-VK.image.extended_usage_bit.texture_write.r8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8snorm, "dEQP-VK.image.extended_usage_bit.texture_write.r8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8uscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8sscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8uint, "dEQP-VK.image.extended_usage_bit.texture_write.r8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8sint, "dEQP-VK.image.extended_usage_bit.texture_write.r8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8unorm, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8snorm, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8uscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8sscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8uint, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8sint, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16unorm, "dEQP-VK.image.extended_usage_bit.texture_write.r16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16snorm, "dEQP-VK.image.extended_usage_bit.texture_write.r16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16uscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16sscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16uint, "dEQP-VK.image.extended_usage_bit.texture_write.r16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16sint, "dEQP-VK.image.extended_usage_bit.texture_write.r16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16sfloat, "dEQP-VK.image.extended_usage_bit.texture_write.r16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8b8a8unorm, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8b8a8_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8b8a8snorm, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8b8a8_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8b8a8uscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8b8a8_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8b8a8sscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8b8a8_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8b8a8uint, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8b8a8_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR8g8b8a8sint, "dEQP-VK.image.extended_usage_bit.texture_write.r8g8b8a8_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteA8b8g8r8unormpack32, "dEQP-VK.image.extended_usage_bit.texture_write.a8b8g8r8_unorm_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteA8b8g8r8snormpack32, "dEQP-VK.image.extended_usage_bit.texture_write.a8b8g8r8_snorm_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteA8b8g8r8uscaledpack32, "dEQP-VK.image.extended_usage_bit.texture_write.a8b8g8r8_uscaled_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteA8b8g8r8sscaledpack32, "dEQP-VK.image.extended_usage_bit.texture_write.a8b8g8r8_sscaled_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteA8b8g8r8uintpack32, "dEQP-VK.image.extended_usage_bit.texture_write.a8b8g8r8_uint_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteA8b8g8r8sintpack32, "dEQP-VK.image.extended_usage_bit.texture_write.a8b8g8r8_sint_pack32*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16unorm, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16snorm, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16uscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16sscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16uint, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16sint, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16sfloat, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR32uint, "dEQP-VK.image.extended_usage_bit.texture_write.r32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR32sint, "dEQP-VK.image.extended_usage_bit.texture_write.r32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR32sfloat, "dEQP-VK.image.extended_usage_bit.texture_write.r32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16b16a16unorm, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16b16a16_unorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16b16a16snorm, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16b16a16_snorm*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16b16a16uscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16b16a16_uscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16b16a16sscaled, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16b16a16_sscaled*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16b16a16uint, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16b16a16_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16b16a16sint, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16b16a16_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR16g16b16a16sfloat, "dEQP-VK.image.extended_usage_bit.texture_write.r16g16b16a16_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR32g32uint, "dEQP-VK.image.extended_usage_bit.texture_write.r32g32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR32g32sint, "dEQP-VK.image.extended_usage_bit.texture_write.r32g32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR32g32sfloat, "dEQP-VK.image.extended_usage_bit.texture_write.r32g32_sfloat*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR32g32b32a32uint, "dEQP-VK.image.extended_usage_bit.texture_write.r32g32b32a32_uint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR32g32b32a32sint, "dEQP-VK.image.extended_usage_bit.texture_write.r32g32b32a32_sint*");
static SHRINK_HWTEST_F(ActsImage0017TS, TCTexturewriteR32g32b32a32sfloat, "dEQP-VK.image.extended_usage_bit.texture_write.r32g32b32a32_sfloat*");