
/**
 * Copyright (c) 2023 iSoftStone Information Technology (Group) Co.,Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { describe, beforeAll, beforeEach, afterEach, afterAll, it, expect } from "@ohos/hypium";
import router from '@ohos.router';
import CommonFunc from '../../../../MainAbility/common/Common';
export default function grid_RowCol_ItemPositionTest() {
  describe('Grid_RowCol_ItemPositionTest', function () {
    beforeEach(async function (done) {
      console.info("Grid_RowCol_ItemPositionTest beforeEach start");
      let options = {
        url: 'MainAbility/pages/Grid/GridTemplatesAllSet/GridItemChange/Grid_RowCol_ItemPosition',
      }
      try {
        router.clear();
        let pages = router.getState();
        console.info("get Grid_RowCol_ItemPosition state pages:" + JSON.stringify(pages));
        if (!("Grid_RowCol_ItemPosition" == pages.name)) {
          console.info("get Grid_RowCol_ItemPosition state pages.name:" + JSON.stringify(pages.name));
          let result = await router.push(options);
          await CommonFunc.sleep(2000);
          console.info("push Grid_RowCol_ItemPosition page result:" + JSON.stringify(result));
        }
      } catch (err) {
        console.error("push Grid_RowCol_ItemPosition page error:" + err);
      }
      console.info("Grid_RowCol_ItemPositionTest beforeEach end");
      done();
    });
    afterEach(async function () {
      await CommonFunc.sleep(1000);
      console.info("Grid_RowCol_ItemPositionTest after each called");
    });
    /**
     * @tc.number    SUB_ACE_GRID_GRIDTEMPLATESALLSET_GRIDITEMCHANGE_0500
     * @tc.name      testGridRowColItemPosition
     * @tc.desc      The second griditem set position to {x:20,y:20}
     */
    it('testGridRowColItemPosition', 0, async function (done) {
      console.info('[testGridRowColItemPosition] START');
      globalThis.value.message.notify({name:'secondGridItemPosition', value:{x:20,y:20}});
      await CommonFunc.sleep(3000);
      let firstGridItem = CommonFunc.getComponentRect('Grid_RowCol_ItemPosition01');
      let secondGridItem = CommonFunc.getComponentRect('Grid_RowCol_ItemPosition02');
      let thirdGridItem = CommonFunc.getComponentRect('Grid_RowCol_ItemPosition03');
      let fourthGridItem = CommonFunc.getComponentRect('Grid_RowCol_ItemPosition04');
      let gridContainer = CommonFunc.getComponentRect('Grid_RowCol_ItemPosition_Container01');
      let gridContainerStrJson = getInspectorByKey('Grid_RowCol_ItemPosition_Container01');
      let gridContainerObj = JSON.parse(gridContainerStrJson);
      expect(gridContainerObj.$type).assertEqual('Grid');

      expect(Math.round(secondGridItem.left - gridContainer.left) - Math.round(vp2px(20)) <= 1).assertTrue();
      expect(Math.round(secondGridItem.top - gridContainer.top) - Math.round(vp2px(20)) <=1).assertTrue(); //position {x:20,y:20}

      expect(firstGridItem.left - gridContainer.left <=1).assertTrue();
      expect(firstGridItem.top - gridContainer.top <=1).assertTrue();
      expect(thirdGridItem.left - gridContainer.left <=1).assertTrue();
      expect(thirdGridItem.top - firstGridItem.bottom <=1).assertTrue();
      expect(fourthGridItem.left - thirdGridItem.right <=1).assertTrue();
      expect(fourthGridItem.top - thirdGridItem.top <=1).assertTrue();

      expect(Math.round(firstGridItem.right - firstGridItem.left) - Math.round(vp2px(150)) <=1).assertTrue();
      expect(Math.round(firstGridItem.bottom - firstGridItem.top) - Math.round(vp2px(150)) <=1).assertTrue();

      expect(Math.round(secondGridItem.right - secondGridItem.left) - Math.round(vp2px(150)) <=1).assertTrue();
      expect(Math.round(secondGridItem.bottom - secondGridItem.top) - Math.round(vp2px(150)) <=1).assertTrue();

      expect(Math.round(thirdGridItem.right - thirdGridItem.left) - Math.round(vp2px(150)) <=1).assertTrue();
      expect(Math.round(thirdGridItem.bottom - thirdGridItem.top) - Math.round(vp2px(150)) <=1).assertTrue();

      expect(Math.round(fourthGridItem.right - fourthGridItem.left) - Math.round(vp2px(150)) <=1).assertTrue();
      expect(Math.round(fourthGridItem.bottom - fourthGridItem.top) - Math.round(vp2px(150)) <=1).assertTrue();
      console.info('[testGridRowColItemPosition] END');
      done();
    });
  })
}
