/**
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import Grid_ReachStartAndEnd from './GridTest/Grid_scroll/Grid_ReachStartAndEnd.test';
import Grid_ReachStartAndEnd2 from './GridTest/Grid_scroll/Grid_ReachStartAndEnd2.test';
import Grid_ReachStartAndEnd3 from './GridTest/Grid_scroll/Grid_ReachStartAndEnd3.test';
import Grid_ReachStartAndEnd4 from './GridTest/Grid_scroll/Grid_ReachStartAndEnd4.test';
import Grid_ReachStartAndEnd5 from './GridTest/Grid_scroll/Grid_ReachStartAndEnd5.test';
import Grid_ScrollStartAndStop from './GridTest/Grid_scroll/Grid_ScrollStartAndStop.test';
import Grid_ScrollStartAndStop2 from './GridTest/Grid_scroll/Grid_ScrollStartAndStop2.test';
import Grid_ScrollStartAndStop3 from './GridTest/Grid_scroll/Grid_ScrollStartAndStop3.test';
import Grid_ScrollStartAndStop4 from './GridTest/Grid_scroll/Grid_ScrollStartAndStop4.test';
import Grid_ScrollAndScrollIndex from './GridTest/Grid_scroll/Grid_ScrollAndScrollIndex.test';
import Grid_ScrollFrameBegin from './GridTest/Grid_scroll/Grid_ScrollFrameBegin.test';
import Grid_RowCol_TemplateChange
  from './GridTest/GridTemplatesAllSet/GridTemplateChange/Grid_RowCol_TemplateChange.test.ets';
import Grid_RowCol_GridSize from './GridTest/GridTemplatesAllSet/GridChange/Grid_RowCol_GridSize.test.ets';
import Grid_RowCol_PadMar from './GridTest/GridTemplatesAllSet/GridChange/Grid_RowCol_PadMar.test.ets';
import Grid_RowCol_Gap from './GridTest/GridTemplatesAllSet/GridChange/Grid_RowCol_Gap.test.ets';
import Grid_RowCol_LayoutDirection from './GridTest/GridTemplatesAllSet/GridChange/Grid_RowCol_LayoutDirection.test.ets';
import Grid_RowCol_maxCount from './GridTest/GridTemplatesAllSet/GridChange/Grid_RowCol_maxCount.test.ets';
import Grid_RowCol_cellLength from './GridTest/GridTemplatesAllSet/GridChange/Grid_RowCol_cellLength.test.ets';
import grid_RowCol_ItemPadMarTest from './GridTest/GridTemplatesAllSet/GridItemChange/Grid_RowCol_ItemPadMar.test';
import grid_RowCol_ItemOffsetTest from './GridTest/GridTemplatesAllSet/GridItemChange/Grid_RowCol_ItemOffset.test';
import grid_RowCol_ItemPositionTest from './GridTest/GridTemplatesAllSet/GridItemChange/Grid_RowCol_ItemPosition.test';
import grid_RowCol_ItemVisibilityTest from './GridTest/GridTemplatesAllSet/GridItemChange/Grid_RowCol_ItemVisibility.test';
import grid_RowCol_ItemContentSizeTest
  from './GridTest/GridTemplatesAllSet/GridItemChange/Grid_RowCol_ItemContentSize.test';
import grid_RowCol_ItemColumnStartEnd
  from './GridTest/GridTemplatesAllSet/GridItemChange/Grid_RowCol_ItemColumnStartEnd.test';
import grid_RowCol_ItemRowStartEnd from './GridTest/GridTemplatesAllSet/GridItemChange/Grid_RowCol_ItemRowStartEnd.test';
import grid_GridFrictionTest from './GridTest/Grid_attribute/Grid_GridFriction.test';
import GridIrregular from "./GridTest/Grid_iiregular/GridIrregular.test";
import GridIrregular1 from "./GridTest/Grid_iiregular/GridIrregular1.test";
import GridIrregular2 from "./GridTest/Grid_iiregular/GridIrregular2.test";
import GridIrregular3 from "./GridTest/Grid_iiregular/GridIrregular3.test";
import onGetIrregular from "./GridTest/Grid_iiregular/onGetIrregular.test";
import onGetIrregular1 from "./GridTest/Grid_iiregular/onGetIrregular1.test";
import onGetIrregular2 from "./GridTest/Grid_iiregular/onGetIrregular2.test";
import onGetIrregular3 from "./GridTest/Grid_iiregular/onGetIrregular3.test";
import onGetIrregular4 from "./GridTest/Grid_iiregular/onGetIrregular4.test";
import onGetIrregular5 from "./GridTest/Grid_iiregular/onGetIrregular5.test";
import onGetIrregular6 from "./GridTest/Grid_iiregular/onGetIrregular6.test";
import onGetIrregular7 from "./GridTest/Grid_iiregular/onGetIrregular7.test";
import onGetIrregular8 from "./GridTest/Grid_iiregular/onGetIrregular8.test";
import onGetIrregular9 from "./GridTest/Grid_iiregular/onGetIrregular9.test";
import Grid_Row_Columns from './GridTest/Grid_Row/Grid_Row_Columns/Grid_Row_Columns.test.ets';
import Grid_Row_Columns_Default from './GridTest/Grid_Row/Grid_Row_Columns/Grid_Row_Columns_Default.test.ets';
import Grid_Row_Columns_Option from './GridTest/Grid_Row/Grid_Row_Columns/Grid_Row_Columns_Option.test.ets';
import Grid_Row_Gutter from './GridTest/Grid_Row/Grid_Row_Gutter/Grid_Row_Gutter.test.ets';
import Grid_Row_Length_String from './GridTest/Grid_Row/Grid_Row_Gutter/Grid_Row_Length_String.test';
import Gutter_Length_Resource from './GridTest/Grid_Row/Grid_Row_Gutter/Grid_Row_Resource.test';
import Gutter_Length_Default from './GridTest/Grid_Row/Grid_Row_Gutter/Grid_Row_Default.test';
import Grid_Row_SizeOption from './GridTest/Grid_Row/Grid_Row_GutterOption/Grid_Row_SizeOption.test';
import Grid_Row_GutterOption_String from './GridTest/Grid_Row/Grid_Row_GutterOption/Grid_Row_GutterOption_String.test';
import Grid_Row_GutterOption_Default from './GridTest/Grid_Row/Grid_Row_GutterOption/Grid_Row_GutterOption_Default.test';
import Grid_Row_GutterOption_Number from './GridTest/Grid_Row/Grid_Row_GutterOption/Grid_Row_GutterOption_Number.test';
import Grid_Row_Direction_Row from './GridTest/Grid_Row/Grid_Row_Direction/Grid_Row_Direction_Row.test';
import Grid_Row_Direction_RowReverse from './GridTest/Grid_Row/Grid_Row_Direction/Grid_Row_Direction_RowReverse.test';
import Grid_Row_Breakpoints_Default from './GridTest/Grid_Row/Grid_Row_Breakpoints/Grid_Row_Breakpoints_Default.test';
import Grid_Row_Breakpoints_Component from './GridTest/Grid_Row/Grid_Row_Breakpoints/Grid_Row_Breakpoints_Component.test';
import Grid_Row_Breakpoints_Window from './GridTest/Grid_Row/Grid_Row_Breakpoints/Grid_Row_Breakpoints_Window.test';
import Grid_Row_Breakpoints_Change from './GridTest/Grid_Row/Grid_Row_Breakpoints/Grid_Row_Breakpoints_Change.test';
import Grid_Row_Breakpoints_Incremental
  from './GridTest/Grid_Row/Grid_Row_Breakpoints/Grid_Row_Breakpoints_Incremental.test';
import Grid_Row_Breakpoints_Negative from './GridTest/Grid_Row/Grid_Row_Breakpoints/Grid_Row_Breakpoints_Negative.test';
import Grid_Row_Breakpoints_Quantity from './GridTest/Grid_Row/Grid_Row_Breakpoints/Grid_Row_Breakpoints_Quantity.test';
import GridRow_onBreakpoint from './GridTest/Grid_Row/onBreakpointChange/onBreakpointChange.test';
import colorGradientJsunit from './Row/ColorGradientJsunit.test';
import enumsImageJsunit from './Row/EnmusImageJsunit.test';
import enumsVerticalAlignJsunit from './Row/EnmusVerticalAlignJsunit.test';
import transFormJsunit from './Row/TransFormJsunit.test';
import VisibilityJsunit from './Row/VisibilityJsunit.test';
import rowJsunit from './Row/RowJsunit.test';
import Grid_Col_Span_Default from './GridColTest/Grid_Col_Span/Grid_Col_Span_Default.test.ets';
import Grid_Col_Span_Number from './GridColTest/Grid_Col_Span/Grid_Col_Span_Number.test.ets';
import Grid_Col_Span_GridColColumnOption from './GridColTest/Grid_Col_Span/Grid_Col_Span_GridColColumnOption.test.ets';
import Grid_Col_Order_Default from './GridColTest/Grid_Col_Order/Grid_Col_Order_Default.test.ets';
import Grid_Col_Order_Number from './GridColTest/Grid_Col_Order/Grid_Col_Order_Number.test.ets';
import Grid_Col_Order_GridColColumnOption from './GridColTest/Grid_Col_Order/Grid_Col_Order_GridColColumnOption.test.ets';
import Grid_Col_Offset_Default from './GridColTest/Grid_Col_Offset/Grid_Col_Offset_Default.test.ets';
import Grid_Col_Offset_Number from './GridColTest/Grid_Col_Offset/Grid_Col_Offset_Number.test.ets';
import Grid_Col_Offset_GridColColumnOption from './GridColTest/Grid_Col_Offset/Grid_Col_Offset_GridColColumnOption.test.ets';
import GridRowJsunit from './GridTest/GridRowJsunit.test.ets';
import GridItemJsunit from './GridTest/GridItemJsunit.test.ets';
import GridColOffsetJsunit from './GridTest/GridColoffsetJsunit.test.ets';
import GridCallbackJsunit from './GridTest/GridCallbackJsunit.test.ets';
import GridRowCol from './GridTest/GridRowCol.test';
import GridRowCol02 from './GridTest/GridRowCol02.test.ets';
import GridLayoutDirection from './GridTest/GridLayoutDirection.test.ets';
import GridJsunit from './GridTest/GridJsunit.test.ets';


export default function testsuite() {
  Grid_ReachStartAndEnd();
  Grid_ScrollStartAndStop();
  Grid_ReachStartAndEnd2();
  Grid_ScrollStartAndStop2();
  Grid_ReachStartAndEnd3();
  Grid_ScrollStartAndStop3();
  Grid_ReachStartAndEnd4();
  Grid_ScrollStartAndStop4();
  Grid_ReachStartAndEnd5();
  Grid_ScrollAndScrollIndex();
  Grid_ScrollFrameBegin();
  Grid_RowCol_TemplateChange()
  Grid_RowCol_GridSize()
  Grid_RowCol_PadMar()
  Grid_RowCol_Gap()
  Grid_RowCol_LayoutDirection()
  Grid_RowCol_maxCount()
  Grid_RowCol_cellLength()
  grid_RowCol_ItemPadMarTest();
  grid_RowCol_ItemOffsetTest();
  grid_RowCol_ItemPositionTest();
  grid_RowCol_ItemVisibilityTest();
  grid_RowCol_ItemContentSizeTest();
  grid_RowCol_ItemColumnStartEnd()
  grid_RowCol_ItemRowStartEnd()
  grid_GridFrictionTest();
  GridIrregular()
  GridIrregular1()
  GridIrregular2()
  GridIrregular3()
  Grid_Row_Columns()
  Grid_Row_Columns_Option()
  Grid_Row_Columns_Default()
  Grid_Row_Gutter()
  Gutter_Length_Resource()
  Gutter_Length_Default()
  Grid_Row_GutterOption_Number()
  Grid_Row_GutterOption_Default()
  Grid_Row_Direction_Row()
  Grid_Row_Direction_RowReverse()
  Grid_Row_Length_String()
  Grid_Row_SizeOption()
  Grid_Row_GutterOption_String()
  Grid_Row_Breakpoints_Default()
  Grid_Row_Breakpoints_Component()
  Grid_Row_Breakpoints_Window()
  Grid_Row_Breakpoints_Change()
  Grid_Row_Breakpoints_Incremental()
  Grid_Row_Breakpoints_Negative()
  Grid_Row_Breakpoints_Quantity()
  GridRow_onBreakpoint()
  colorGradientJsunit()
  enumsImageJsunit()
  transFormJsunit()
  VisibilityJsunit()
  rowJsunit()
  Grid_Col_Span_Default()
  Grid_Col_Span_Number()
  Grid_Col_Span_GridColColumnOption()
  Grid_Col_Order_Default()
  Grid_Col_Order_Number()
  Grid_Col_Order_GridColColumnOption()
  Grid_Col_Offset_Default()
  Grid_Col_Offset_Number()
  Grid_Col_Offset_GridColColumnOption()
  GridRowJsunit();
  GridItemJsunit();
  GridColOffsetJsunit();
  GridCallbackJsunit();
  GridRowCol();
  GridRowCol02();
  GridLayoutDirection();
  GridJsunit();
  onGetIrregular()
  onGetIrregular1()
  onGetIrregular2()
  onGetIrregular3()
  onGetIrregular4()
  onGetIrregular5()
  onGetIrregular6()
  onGetIrregular7()
  onGetIrregular8()
  onGetIrregular9()
}