/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import attrsManager from '../../common/AttrsManager'
import router from '@ohos.router'

class AlphabetIndexerModifier implements AttributeModifier<AlphabetIndexerAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: AlphabetIndexerAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class BadgeModifier implements AttributeModifier<BadgeAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: BadgeAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ButtonModifier implements AttributeModifier<ButtonAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ButtonAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class BlankModifier implements AttributeModifier<BlankAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: BlankAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class CalendarPickerModifier implements AttributeModifier<CalendarPickerAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: CalendarPickerAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class CanvasModifier implements AttributeModifier<CanvasAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: CanvasAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class CheckboxModifier implements AttributeModifier<CheckboxAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: CheckboxAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class CheckboxGroupModifier implements AttributeModifier<CheckboxGroupAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: CheckboxGroupAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class CircleModifier implements AttributeModifier<CircleAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: CircleAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ColumnModifier implements AttributeModifier<ColumnAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ColumnAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ColumnSplitModifier implements AttributeModifier<ColumnSplitAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ColumnSplitAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class CounterModifier implements AttributeModifier<CounterAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: CounterAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class DataPanelModifier implements AttributeModifier<DataPanelAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: DataPanelAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class DatePickerModifier implements AttributeModifier<DatePickerAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: DatePickerAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class DividerModifier implements AttributeModifier<DividerAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: DividerAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class EllipseModifier implements AttributeModifier<EllipseAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: EllipseAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class FlexModifier implements AttributeModifier<FlexAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: FlexAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class FlowItemModifier implements AttributeModifier<FlowItemAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: FlowItemAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class FormLinkModifier implements AttributeModifier<FormLinkAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: FormLinkAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class GaugeModifier implements AttributeModifier<GaugeAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: GaugeAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class GridModifier implements AttributeModifier<GridAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: GridAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class GridColModifier implements AttributeModifier<GridColAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: GridColAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class GridItemModifier implements AttributeModifier<GridItemAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: GridItemAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class GridRowModifier implements AttributeModifier<GridRowAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: GridRowAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class HyperlinkModifier implements AttributeModifier<HyperlinkAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: HyperlinkAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ImageModifier implements AttributeModifier<ImageAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ImageAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ImageAnimatorModifier implements AttributeModifier<ImageAnimatorAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ImageAnimatorAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class LineModifier implements AttributeModifier<LineAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: LineAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ListModifier implements AttributeModifier<ListAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ListAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ListItemModifier implements AttributeModifier<ListItemAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ListItemAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ListItemGroupModifier implements AttributeModifier<ListItemGroupAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ListItemGroupAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class LoadingProgressModifier implements AttributeModifier<LoadingProgressAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: LoadingProgressAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class MarqueeModifier implements AttributeModifier<MarqueeAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: MarqueeAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class MenuModifier implements AttributeModifier<MenuAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: MenuAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class MenuItemModifier implements AttributeModifier<MenuItemAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: MenuItemAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class MenuItemGroupModifier implements AttributeModifier<MenuItemGroupAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: MenuItemGroupAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class NavDestinationModifier implements AttributeModifier<NavDestinationAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: NavDestinationAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class NavigationModifier implements AttributeModifier<NavigationAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: NavigationAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class NavigatorModifier implements AttributeModifier<NavigatorAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: NavigatorAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class NavRouterModifier implements AttributeModifier<NavRouterAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: NavRouterAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class PanelModifier implements AttributeModifier<PanelAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: PanelAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class PathModifier implements AttributeModifier<PathAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: PathAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class PolygonModifier implements AttributeModifier<PolygonAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: PolygonAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class PolylineModifier implements AttributeModifier<PolylineAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: PolylineAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ProgressModifier implements AttributeModifier<ProgressAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ProgressAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class QRCodeModifier implements AttributeModifier<QRCodeAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: QRCodeAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RadioModifier implements AttributeModifier<RadioAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RadioAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RatingModifier implements AttributeModifier<RatingAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RatingAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RectModifier implements AttributeModifier<RectAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RectAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RefreshModifier implements AttributeModifier<RefreshAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RefreshAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RelativeContainerModifier implements AttributeModifier<RelativeContainerAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RelativeContainerAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RemoteWindowModifier implements AttributeModifier<RemoteWindowAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RemoteWindowAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RichEditorModifier implements AttributeModifier<RichEditorAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RichEditorAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RichTextModifier implements AttributeModifier<RichTextAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RichTextAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RowModifier implements AttributeModifier<RowAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RowAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class RowSplitModifier implements AttributeModifier<RowSplitAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: RowSplitAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ScrollModifier implements AttributeModifier<ScrollAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ScrollAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ScrollBarModifier implements AttributeModifier<ScrollBarAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ScrollBarAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class SearchModifier implements AttributeModifier<SearchAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: SearchAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class SelectModifier implements AttributeModifier<SelectAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: SelectAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ShapeModifier implements AttributeModifier<ShapeAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ShapeAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class SideBarContainerModifier implements AttributeModifier<SideBarContainerAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: SideBarContainerAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class SliderModifier implements AttributeModifier<SliderAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: SliderAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class SpanModifier implements AttributeModifier<SpanAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: SpanAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class StackModifier implements AttributeModifier<StackAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: StackAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class StepperModifier implements AttributeModifier<StepperAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: StepperAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class StepperItemModifier implements AttributeModifier<StepperItemAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: StepperItemAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class SwiperModifier implements AttributeModifier<SwiperAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: SwiperAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class TabContentModifier implements AttributeModifier<TabContentAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: TabContentAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class TabsModifier implements AttributeModifier<TabsAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: TabsAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class TextModifier implements AttributeModifier<TextAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: TextAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class TextAreaModifier implements AttributeModifier<TextAreaAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: TextAreaAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class TextClockModifier implements AttributeModifier<TextClockAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: TextClockAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class TextInputModifier implements AttributeModifier<TextInputAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: TextInputAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class TextPickerModifier implements AttributeModifier<TextPickerAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: TextPickerAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class TextTimerModifier implements AttributeModifier<TextTimerAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: TextTimerAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class TimePickerModifier implements AttributeModifier<TimePickerAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: TimePickerAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class ToggleModifier implements AttributeModifier<ToggleAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: ToggleAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class VideoModifier implements AttributeModifier<VideoAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: VideoAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class WaterFlowModifier implements AttributeModifier<WaterFlowAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: WaterFlowAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class WebModifier implements AttributeModifier<WebAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: WebAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class WindowSceneModifier implements AttributeModifier<WindowSceneAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: WindowSceneAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

class XComponentModifier implements AttributeModifier<XComponentAttribute> {
	mClickEffect: ClickEffect = { level: ClickEffectLevel.HEAVY, scale: 0.9 }

	applyNormalAttribute(instance: XComponentAttribute): void {
		instance.clickEffect(this.mClickEffect)
	}
}

@Entry
@Component
struct ClickEffectPage {
	@State _clickEffectAlphabetIndexerModifier: AlphabetIndexerModifier = new AlphabetIndexerModifier()
	@State _clickEffectBadgeModifier: BadgeModifier = new BadgeModifier()
	@State _clickEffectButtonModifier: ButtonModifier = new ButtonModifier()
	@State _clickEffectBlankModifier: BlankModifier = new BlankModifier()
	@State _clickEffectCalendarPickerModifier: CalendarPickerModifier = new CalendarPickerModifier()
	@State _clickEffectCanvasModifier: CanvasModifier = new CanvasModifier()
	@State _clickEffectCheckboxModifier: CheckboxModifier = new CheckboxModifier()
	@State _clickEffectCheckboxGroupModifier: CheckboxGroupModifier = new CheckboxGroupModifier()
	@State _clickEffectCircleModifier: CircleModifier = new CircleModifier()
	@State _clickEffectColumnModifier: ColumnModifier = new ColumnModifier()
	@State _clickEffectColumnSplitModifier: ColumnSplitModifier = new ColumnSplitModifier()
	@State _clickEffectCounterModifier: CounterModifier = new CounterModifier()
	@State _clickEffectDataPanelModifier: DataPanelModifier = new DataPanelModifier()
	@State _clickEffectDatePickerModifier: DatePickerModifier = new DatePickerModifier()
	@State _clickEffectDividerModifier: DividerModifier = new DividerModifier()
	@State _clickEffectEllipseModifier: EllipseModifier = new EllipseModifier()
	@State _clickEffectFlexModifier: FlexModifier = new FlexModifier()
	@State _clickEffectFlowItemModifier: FlowItemModifier = new FlowItemModifier()
	@State _clickEffectFormLinkModifier: FormLinkModifier = new FormLinkModifier()
	@State _clickEffectGaugeModifier: GaugeModifier = new GaugeModifier()
	@State _clickEffectGridModifier: GridModifier = new GridModifier()
	@State _clickEffectGridColModifier: GridColModifier = new GridColModifier()
	@State _clickEffectGridItemModifier: GridItemModifier = new GridItemModifier()
	@State _clickEffectGridRowModifier: GridRowModifier = new GridRowModifier()
	@State _clickEffectHyperlinkModifier: HyperlinkModifier = new HyperlinkModifier()
	@State _clickEffectImageModifier: ImageModifier = new ImageModifier()
	@State _clickEffectImageAnimatorModifier: ImageAnimatorModifier = new ImageAnimatorModifier()
	@State _clickEffectLineModifier: LineModifier = new LineModifier()
	@State _clickEffectListModifier: ListModifier = new ListModifier()
	@State _clickEffectListItemModifier: ListItemModifier = new ListItemModifier()
	@State _clickEffectListItemGroupModifier: ListItemGroupModifier = new ListItemGroupModifier()
	@State _clickEffectLoadingProgressModifier: LoadingProgressModifier = new LoadingProgressModifier()
	@State _clickEffectMarqueeModifier: MarqueeModifier = new MarqueeModifier()
	@State _clickEffectMenuModifier: MenuModifier = new MenuModifier()
	@State _clickEffectMenuItemModifier: MenuItemModifier = new MenuItemModifier()
	@State _clickEffectMenuItemGroupModifier: MenuItemGroupModifier = new MenuItemGroupModifier()
	@State _clickEffectNavDestinationModifier: NavDestinationModifier = new NavDestinationModifier()
	@State _clickEffectNavigationModifier: NavigationModifier = new NavigationModifier()
	@State _clickEffectNavigatorModifier: NavigatorModifier = new NavigatorModifier()
	@State _clickEffectNavRouterModifier: NavRouterModifier = new NavRouterModifier()
	@State _clickEffectPanelModifier: PanelModifier = new PanelModifier()
	@State _clickEffectPathModifier: PathModifier = new PathModifier()
	@State _clickEffectPolygonModifier: PolygonModifier = new PolygonModifier()
	@State _clickEffectPolylineModifier: PolylineModifier = new PolylineModifier()
	@State _clickEffectProgressModifier: ProgressModifier = new ProgressModifier()
	@State _clickEffectQRCodeModifier: QRCodeModifier = new QRCodeModifier()
	@State _clickEffectRadioModifier: RadioModifier = new RadioModifier()
	@State _clickEffectRatingModifier: RatingModifier = new RatingModifier()
	@State _clickEffectRectModifier: RectModifier = new RectModifier()
	@State _clickEffectRefreshModifier: RefreshModifier = new RefreshModifier()
	@State _clickEffectRelativeContainerModifier: RelativeContainerModifier = new RelativeContainerModifier()
	@State _clickEffectRemoteWindowModifier: RemoteWindowModifier = new RemoteWindowModifier()
	@State _clickEffectRichEditorModifier: RichEditorModifier = new RichEditorModifier()
	@State _clickEffectRichTextModifier: RichTextModifier = new RichTextModifier()
	@State _clickEffectRowModifier: RowModifier = new RowModifier()
	@State _clickEffectRowSplitModifier: RowSplitModifier = new RowSplitModifier()
	@State _clickEffectScrollModifier: ScrollModifier = new ScrollModifier()
	@State _clickEffectScrollBarModifier: ScrollBarModifier = new ScrollBarModifier()
	@State _clickEffectSearchModifier: SearchModifier = new SearchModifier()
	@State _clickEffectSelectModifier: SelectModifier = new SelectModifier()
	@State _clickEffectShapeModifier: ShapeModifier = new ShapeModifier()
	@State _clickEffectSideBarContainerModifier: SideBarContainerModifier = new SideBarContainerModifier()
	@State _clickEffectSliderModifier: SliderModifier = new SliderModifier()
	@State _clickEffectSpanModifier: SpanModifier = new SpanModifier()
	@State _clickEffectStackModifier: StackModifier = new StackModifier()
	@State _clickEffectStepperModifier: StepperModifier = new StepperModifier()
	@State _clickEffectStepperItemModifier: StepperItemModifier = new StepperItemModifier()
	@State _clickEffectSwiperModifier: SwiperModifier = new SwiperModifier()
	@State _clickEffectTabContentModifier: TabContentModifier = new TabContentModifier()
	@State _clickEffectTabsModifier: TabsModifier = new TabsModifier()
	@State _clickEffectTextModifier: TextModifier = new TextModifier()
	@State _clickEffectTextAreaModifier: TextAreaModifier = new TextAreaModifier()
	@State _clickEffectTextClockModifier: TextClockModifier = new TextClockModifier()
	@State _clickEffectTextInputModifier: TextInputModifier = new TextInputModifier()
	@State _clickEffectTextPickerModifier: TextPickerModifier = new TextPickerModifier()
	@State _clickEffectTextTimerModifier: TextTimerModifier = new TextTimerModifier()
	@State _clickEffectTimePickerModifier: TimePickerModifier = new TimePickerModifier()
	@State _clickEffectToggleModifier: ToggleModifier = new ToggleModifier()
	@State _clickEffectVideoModifier: VideoModifier = new VideoModifier()
	@State _clickEffectWaterFlowModifier: WaterFlowModifier = new WaterFlowModifier()
	@State _clickEffectWebModifier: WebModifier = new WebModifier()
	@State _clickEffectWindowSceneModifier: WindowSceneModifier = new WindowSceneModifier()
	@State _clickEffectXComponentModifier: XComponentModifier = new XComponentModifier()
	@State targetView: string = router.getParams() ? (router.getParams() as ESObject)['view']['targetView'] : ''
	@State componentKey: string = router.getParams() ? (router.getParams() as ESObject)['view']['componentKey'] : ''
	@State parentWidth: number = router.getParams() ? (router.getParams() as ESObject)['view']['parentWidth'] : 0
	@State parentHeight: number = router.getParams() ? (router.getParams() as ESObject)['view']['parentHeight'] : 0
	@State columns: number = router.getParams() ? (router.getParams() as ESObject)['view']['columns'] : 0
	@State gutter: number = router.getParams() ? (router.getParams() as ESObject)['view']['gutter'] : 0
	@State parentBackGroundColor: string = router.getParams() ? (router.getParams() as ESObject)['view']['parentBackGroundColor'] : '#FFFF00'
	@State parentComponentKey: string = router.getParams() ? (router.getParams() as ESObject)['view']['parentComponentKey'] : ''

	onPageShow() {
		console.info('clickEffect translate page show called ')
		attrsManager.registerDataChange((value:ESObject) => {
			console.info('clickEffect [registerDataChange] ' + JSON.stringify(value.clickEffect))
			this._clickEffectAlphabetIndexerModifier.mClickEffect = value.clickEffect
			this._clickEffectBadgeModifier.mClickEffect = value.clickEffect
			this._clickEffectButtonModifier.mClickEffect = value.clickEffect
			this._clickEffectBlankModifier.mClickEffect = value.clickEffect
			this._clickEffectCalendarPickerModifier.mClickEffect = value.clickEffect
			this._clickEffectCanvasModifier.mClickEffect = value.clickEffect
			this._clickEffectCheckboxModifier.mClickEffect = value.clickEffect
			this._clickEffectCheckboxGroupModifier.mClickEffect = value.clickEffect
			this._clickEffectCircleModifier.mClickEffect = value.clickEffect
			this._clickEffectColumnModifier.mClickEffect = value.clickEffect
			this._clickEffectColumnSplitModifier.mClickEffect = value.clickEffect
			this._clickEffectCounterModifier.mClickEffect = value.clickEffect
			this._clickEffectDataPanelModifier.mClickEffect = value.clickEffect
			this._clickEffectDatePickerModifier.mClickEffect = value.clickEffect
			this._clickEffectDividerModifier.mClickEffect = value.clickEffect
			this._clickEffectEllipseModifier.mClickEffect = value.clickEffect
			this._clickEffectFlexModifier.mClickEffect = value.clickEffect
			this._clickEffectFlowItemModifier.mClickEffect = value.clickEffect
			this._clickEffectFormLinkModifier.mClickEffect = value.clickEffect
			this._clickEffectGaugeModifier.mClickEffect = value.clickEffect
			this._clickEffectGridModifier.mClickEffect = value.clickEffect
			this._clickEffectGridColModifier.mClickEffect = value.clickEffect
			this._clickEffectGridItemModifier.mClickEffect = value.clickEffect
			this._clickEffectGridRowModifier.mClickEffect = value.clickEffect
			this._clickEffectHyperlinkModifier.mClickEffect = value.clickEffect
			this._clickEffectImageModifier.mClickEffect = value.clickEffect
			this._clickEffectImageAnimatorModifier.mClickEffect = value.clickEffect
			this._clickEffectLineModifier.mClickEffect = value.clickEffect
			this._clickEffectListModifier.mClickEffect = value.clickEffect
			this._clickEffectListItemModifier.mClickEffect = value.clickEffect
			this._clickEffectListItemGroupModifier.mClickEffect = value.clickEffect
			this._clickEffectLoadingProgressModifier.mClickEffect = value.clickEffect
			this._clickEffectMarqueeModifier.mClickEffect = value.clickEffect
			this._clickEffectMenuModifier.mClickEffect = value.clickEffect
			this._clickEffectMenuItemModifier.mClickEffect = value.clickEffect
			this._clickEffectMenuItemGroupModifier.mClickEffect = value.clickEffect
			this._clickEffectNavDestinationModifier.mClickEffect = value.clickEffect
			this._clickEffectNavigationModifier.mClickEffect = value.clickEffect
			this._clickEffectNavigatorModifier.mClickEffect = value.clickEffect
			this._clickEffectNavRouterModifier.mClickEffect = value.clickEffect
			this._clickEffectPanelModifier.mClickEffect = value.clickEffect
			this._clickEffectPathModifier.mClickEffect = value.clickEffect
			this._clickEffectPolygonModifier.mClickEffect = value.clickEffect
			this._clickEffectPolylineModifier.mClickEffect = value.clickEffect
			this._clickEffectProgressModifier.mClickEffect = value.clickEffect
			this._clickEffectQRCodeModifier.mClickEffect = value.clickEffect
			this._clickEffectRadioModifier.mClickEffect = value.clickEffect
			this._clickEffectRatingModifier.mClickEffect = value.clickEffect
			this._clickEffectRectModifier.mClickEffect = value.clickEffect
			this._clickEffectRefreshModifier.mClickEffect = value.clickEffect
			this._clickEffectRelativeContainerModifier.mClickEffect = value.clickEffect
			this._clickEffectRemoteWindowModifier.mClickEffect = value.clickEffect
			this._clickEffectRichEditorModifier.mClickEffect = value.clickEffect
			this._clickEffectRichTextModifier.mClickEffect = value.clickEffect
			this._clickEffectRowModifier.mClickEffect = value.clickEffect
			this._clickEffectRowSplitModifier.mClickEffect = value.clickEffect
			this._clickEffectScrollModifier.mClickEffect = value.clickEffect
			this._clickEffectScrollBarModifier.mClickEffect = value.clickEffect
			this._clickEffectSearchModifier.mClickEffect = value.clickEffect
			this._clickEffectSelectModifier.mClickEffect = value.clickEffect
			this._clickEffectShapeModifier.mClickEffect = value.clickEffect
			this._clickEffectSideBarContainerModifier.mClickEffect = value.clickEffect
			this._clickEffectSliderModifier.mClickEffect = value.clickEffect
			this._clickEffectSpanModifier.mClickEffect = value.clickEffect
			this._clickEffectStackModifier.mClickEffect = value.clickEffect
			this._clickEffectStepperModifier.mClickEffect = value.clickEffect
			this._clickEffectStepperItemModifier.mClickEffect = value.clickEffect
			this._clickEffectSwiperModifier.mClickEffect = value.clickEffect
			this._clickEffectTabContentModifier.mClickEffect = value.clickEffect
			this._clickEffectTabsModifier.mClickEffect = value.clickEffect
			this._clickEffectTextModifier.mClickEffect = value.clickEffect
			this._clickEffectTextAreaModifier.mClickEffect = value.clickEffect
			this._clickEffectTextClockModifier.mClickEffect = value.clickEffect
			this._clickEffectTextInputModifier.mClickEffect = value.clickEffect
			this._clickEffectTextPickerModifier.mClickEffect = value.clickEffect
			this._clickEffectTextTimerModifier.mClickEffect = value.clickEffect
			this._clickEffectTimePickerModifier.mClickEffect = value.clickEffect
			this._clickEffectToggleModifier.mClickEffect = value.clickEffect
			this._clickEffectVideoModifier.mClickEffect = value.clickEffect
			this._clickEffectWaterFlowModifier.mClickEffect = value.clickEffect
			this._clickEffectWebModifier.mClickEffect = value.clickEffect
			this._clickEffectWindowSceneModifier.mClickEffect = value.clickEffect
			this._clickEffectXComponentModifier.mClickEffect = value.clickEffect
		})
	}

	@Styles
  commonStyle() {
		.key(this.componentKey)
  }

	build() {
		Column() {
			if (this.targetView == 'AlphabetIndexer') {
				AlphabetIndexer({ arrayValue: ['#', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], selected: 0 })
					.commonStyle()
					.attributeModifier(this._clickEffectAlphabetIndexerModifier)
			}
			if (this.targetView == 'Button') {
				Button('button1')
					.commonStyle()
					.attributeModifier(this._clickEffectButtonModifier)
			}
			if (this.targetView == 'Blank') {
				Blank()
					.backgroundColor(Color.Yellow)
					.commonStyle()
					.attributeModifier(this._clickEffectBlankModifier)
			}
			if (this.targetView == 'Checkbox') {
				Checkbox()
					.commonStyle()
					.attributeModifier(this._clickEffectCheckboxModifier)
			}
			if (this.targetView == 'CheckboxGroup') {
				CheckboxGroup({ group: 'checkboxGroup' })
					.commonStyle()
					.attributeModifier(this._clickEffectCheckboxGroupModifier)
			}
			if (this.targetView == 'DataPanel') {
				DataPanel({ values: [5, 10, 10, 7, 9, 10, 10, 10, 10] })
					.commonStyle()
					.attributeModifier(this._clickEffectDataPanelModifier)
			}
			if (this.targetView == 'DatePicker') {
				DatePicker({ start: new Date('1970-1-1'), end: new Date('2100-1-1') })
					.commonStyle()
					.attributeModifier(this._clickEffectDatePickerModifier)
			}
			if (this.targetView == 'Divider') {
				Divider()
					.commonStyle()
					.attributeModifier(this._clickEffectDividerModifier)
			}
			if (this.targetView == 'Gauge') {
				Gauge({ value: 105 })
					.colors([[0x317AF7, 1], [0x5BA854, 1], [0xE08C3A, 1], [0x9C554B, 1]])
					.commonStyle()
					.attributeModifier(this._clickEffectGaugeModifier)
			}
			if (this.targetView == 'Image') {
				Image($r('app.media.icon'))
					.commonStyle()
					.attributeModifier(this._clickEffectImageModifier)
			}
			if (this.targetView == 'ImageAnimator') {
				ImageAnimator()
					.images([{ src: $r('app.media.icon') }])
					.commonStyle()
					.attributeModifier(this._clickEffectImageAnimatorModifier)
			}
			if (this.targetView == 'LoadingProgress') {
				LoadingProgress()
					.commonStyle()
					.attributeModifier(this._clickEffectLoadingProgressModifier)
			}
			if (this.targetView == 'Marquee') {
				Marquee({ 
					start: true,
					step: 50,
					loop: Infinity,
					fromStart: true,
					src: 'Running Marquee starts rolling'
				})
					.commonStyle()
					.attributeModifier(this._clickEffectMarqueeModifier)
			}
			if (this.targetView == 'Navigation') {
				Navigation() {
				}
					.commonStyle()
					.attributeModifier(this._clickEffectNavigationModifier)
			}
			if (this.targetView == 'Menu') {
				Menu() {
					MenuItem({ startIcon: $r('app.media.icon'), content: 'Menu' })
				}
					.backgroundColor(Color.Yellow)
					.commonStyle()
					.attributeModifier(this._clickEffectMenuModifier)
			}
			if (this.targetView == 'NavRouter') {
				NavRouter() {
					Row() {
						Image($r('app.media.icon'))
					}

					NavDestination() {
						Text('NavDestination')
							.fontSize(10)
					}
				}
					.commonStyle()
					.attributeModifier(this._clickEffectNavRouterModifier)
			}
			if (this.targetView == 'Progress') {
				Progress({ value: 10, type: ProgressType.Eclipse })
					.commonStyle()
					.attributeModifier(this._clickEffectProgressModifier)
			}
			if (this.targetView == 'QRCode') {
				QRCode('Running Marquee starts rolling')
					.commonStyle()
					.attributeModifier(this._clickEffectQRCodeModifier)
			}
			if (this.targetView == 'Radio') {
				Radio({ value: 'Radio1', group: 'radioGroup' })
					.commonStyle()
					.attributeModifier(this._clickEffectRadioModifier)
			}
			if (this.targetView == 'Rating') {
				Rating({ rating: 3.5, indicator: false })
					.commonStyle()
					.attributeModifier(this._clickEffectRatingModifier)
			}
			if (this.targetView == 'ScrollBar') {
				ScrollBar({ scroller: new Scroller(), state: BarState.On }) {
					Text()
						.width(20)
						.height(100)
						.borderRadius(10)
						.backgroundColor('#C0C0C0')
				}
					.commonStyle()
					.attributeModifier(this._clickEffectScrollBarModifier)
			}
			if (this.targetView == 'Search') {
				Search()
					.commonStyle()
					.attributeModifier(this._clickEffectSearchModifier)
			}
			if (this.targetView == 'Select') {
				Select([{ value: 'aaa' }, { value: 'bbb' }])
					.commonStyle()
					.attributeModifier(this._clickEffectSelectModifier)
			}
			if (this.targetView == 'Slider') {
				Slider({ value: 50, min: 0, max: 100, style: SliderStyle.OutSet })
					.showTips(true)
					.commonStyle()
					.attributeModifier(this._clickEffectSliderModifier)
			}
			if (this.targetView == 'Stepper') {
				Stepper() {
					StepperItem() {
						Column() {
							Text('Page One')
						}
					}
				}
					.commonStyle()
					.attributeModifier(this._clickEffectStepperModifier)
			}
			if (this.targetView == 'StepperItem') {
				Stepper() {
					StepperItem() {
						Column() {
							Text('Page One')
						}
					}
						.backgroundColor(Color.Red)
						.commonStyle()
						.attributeModifier(this._clickEffectStepperItemModifier)
				}
					.backgroundColor(Color.Yellow)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'Text') {
				Text('text1')
					.commonStyle()
					.attributeModifier(this._clickEffectTextModifier)
			}
			if (this.targetView == 'TextArea') {
				TextArea({ placeholder: 'The text area can hold an unlimited amount of text. input your word...' })
					.commonStyle()
					.attributeModifier(this._clickEffectTextAreaModifier)
			}
			if (this.targetView == 'TextClock') {
				TextClock({ timeZoneOffset: -8 })
					.format('hms')
					.commonStyle()
					.attributeModifier(this._clickEffectTextClockModifier)
			}
			if (this.targetView == 'TextInput') {
				TextInput({ placeholder: 'input your word...' })
					.commonStyle()
					.attributeModifier(this._clickEffectTextInputModifier)
			}
			if (this.targetView == 'TextPicker') {
				TextPicker({ range: ['#', 'A', 'B', 'C', 'D', 'E', 'F', 'G'] })
					.commonStyle()
					.attributeModifier(this._clickEffectTextPickerModifier)
			}
			if (this.targetView == 'TextTimer') {
				TextTimer({ isCountDown: true, count: 30000 })
					.format('mm:ss.SS')
					.fontColor(Color.Black)
					.commonStyle()
					.attributeModifier(this._clickEffectTextTimerModifier)
			}
			if (this.targetView == 'TimePicker') {
				TimePicker({ selected: new Date('2022-07-22T08:00:00') })
					.commonStyle()
					.attributeModifier(this._clickEffectTimePickerModifier)
			}
			if (this.targetView == 'Toggle') {
				Toggle({ type: ToggleType.Switch, isOn: false })
					.commonStyle()
					.attributeModifier(this._clickEffectToggleModifier)
			}
			if (this.targetView == 'Web') {
				Web({ src: 'www.example.com', controller: new WebController() })
					.commonStyle()
					.attributeModifier(this._clickEffectWebModifier)
			}
			if (this.targetView == 'Circle') {
				Circle()
					.width(150)
					.height(200)
					.commonStyle()
					.attributeModifier(this._clickEffectCircleModifier)
			}
			if (this.targetView == 'Ellipse') {
				Ellipse()
					.commonStyle()
					.attributeModifier(this._clickEffectEllipseModifier)
			}
			if (this.targetView == 'Line') {
				Line()
					.startPoint([0, 0])
					.endPoint([50, 100])
					.backgroundColor(Color.Black)
					.commonStyle()
					.attributeModifier(this._clickEffectLineModifier)
			}
			if (this.targetView == 'Polyline') {
				Polyline()
					.commonStyle()
					.attributeModifier(this._clickEffectPolylineModifier)
			}
			if (this.targetView == 'Polygon') {
				Polygon()
					.commonStyle()
					.attributeModifier(this._clickEffectPolygonModifier)
			}
			if (this.targetView == 'Path') {
				Path()
					.commonStyle()
					.attributeModifier(this._clickEffectPathModifier)
			}
			if (this.targetView == 'Rect') {
				Rect()
					.commonStyle()
					.attributeModifier(this._clickEffectRectModifier)
			}
			if (this.targetView == 'Shape') {
				Shape() {
					Rect()
						.width(100)
						.height(50)
				}
					.commonStyle()
					.attributeModifier(this._clickEffectShapeModifier)
			}
			if (this.targetView == 'Badge') {
				Badge({ count: 50, style: { color: 0xFFFFFF, fontSize: 16, badgeSize: 20, badgeColor: Color.Red } }) {
					Button('message')
						.width(100)
						.height(50)
						.backgroundColor(0x317aff)
				}
					.commonStyle()
					.attributeModifier(this._clickEffectBadgeModifier)
			}
			if (this.targetView == 'Column') {
				Column() {
					Button()
						.width(100)
						.height(50)
				}
					.commonStyle()
					.attributeModifier(this._clickEffectColumnModifier)
			}
			if (this.targetView == 'ColumnSplit') {
				ColumnSplit() {
					Text('1')
						.width('100%')
						.height(50)
						.backgroundColor(0xF5DEB3)
						.textAlign(TextAlign.Center)
				}
					.commonStyle()
					.attributeModifier(this._clickEffectColumnSplitModifier)
			}
			if (this.targetView == 'Counter') {
				Counter() {
				}
					.commonStyle()
					.attributeModifier(this._clickEffectCounterModifier)
			}
			if (this.targetView == 'Flex') {
				Flex() {
					Text('1')
						.width('20%')
						.height(50)
						.backgroundColor(0xF5DEB3)
				}
					.commonStyle()
					.attributeModifier(this._clickEffectFlexModifier)
			}
			if (this.targetView == 'GridRow') {
				GridRow({ columns: 1, direction: GridRowDirection.Row }) {
					ForEach(
						[Color.Red, Color.Orange, Color.Yellow, Color.Green, Color.Pink, Color.Grey, Color.Blue, Color.Brown],
						(color:Color) => {
							GridCol({ span: { xs: 1, sm: 2, md: 3, lg: 4 } }) {
								Row()
									.width('100%')
									.height('20vp')
							}
								.borderColor(color)
								.borderWidth(2)
						}
					)
				}
					.commonStyle()
					.attributeModifier(this._clickEffectGridRowModifier)
			}
			if (this.targetView == 'Grid') {
				Grid() {
					ForEach(['0', '1', '2', '3', '4'], () => {
						ForEach(['0', '1', '2', '3', '4'], (day: string) => {
							GridItem() {
								Text(day)
									.backgroundColor(Color.White)
									.width('100%')
									.height('100%')
									.textAlign(TextAlign.Center)
							}
						})
					})
				}
					.columnsTemplate('1fr 1fr 1fr 1fr 1fr')
					.rowsTemplate('1fr 1fr 1fr 1fr 1fr')
					.backgroundColor(0xFAEEE0)
					.commonStyle()
					.attributeModifier(this._clickEffectGridModifier)
			}
			if (this.targetView == 'List') {
				List() {
				}
					.height('100%')
					.width('100%')
					.commonStyle()
					.attributeModifier(this._clickEffectListModifier)
			}
			if (this.targetView == 'ListItem') {
				List({ space: 20, initialIndex: 0 }) {
					ListItem() {
						Text('item1')
							.width('100%')
							.textAlign(TextAlign.Center)
							.backgroundColor(Color.White)
					}
						.commonStyle()
						.attributeModifier(this._clickEffectListItemModifier)
				}
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'ListItemGroup') {
				List({ space: 0, initialIndex: 0 }) {
					ListItemGroup()
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._clickEffectListItemGroupModifier)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'Navigator') {
				Navigator() {
					Text('Go to back page')
						.width('100%')
						.height(20)
				}
					.backgroundColor(Color.Red)
					.commonStyle()
					.attributeModifier(this._clickEffectNavigatorModifier)
			}
			if (this.targetView == 'Panel') {
				Panel(true) {
					Text('Text')
				}
					.backgroundColor(Color.Yellow)
					.commonStyle()
					.attributeModifier(this._clickEffectPanelModifier)
			}
			if (this.targetView == 'Refresh') {
				Refresh({ refreshing: true }) {
					Text('123')
				}
					.commonStyle()
					.attributeModifier(this._clickEffectRefreshModifier)
			}
			if (this.targetView == 'RelativeContainer') {
				RelativeContainer() {
					Row()
						.width(100)
						.height(100)
						.backgroundColor('#FF3333')
						.alignRules({
							top: { anchor: '__container__', align: VerticalAlign.Top },
							left: { anchor: '__container__', align: HorizontalAlign.Start }
						})
						.id('constraintSize')
				}
					.commonStyle()
					.attributeModifier(this._clickEffectRelativeContainerModifier)
			}
			if (this.targetView == 'Row') {
				Row()
					.commonStyle()
					.attributeModifier(this._clickEffectRowModifier)
			}
			if (this.targetView == 'RowSplit') {
				RowSplit() {
					Text('Text')
				}
					.commonStyle()
					.attributeModifier(this._clickEffectRowSplitModifier)
			}
			if (this.targetView == 'Scroll') {
				Scroll() {
					Column() {
						ForEach([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], (item:number) => {
							Text('Scroll' + item.toString())
								.width('90%')
								.height(50)
								.backgroundColor(Color.White)
								.textAlign(TextAlign.Center)
						}, (item:number) => item.toString())
					}
					.width('100%')
				}
					.scrollBar(BarState.On)
					.commonStyle()
					.attributeModifier(this._clickEffectScrollModifier)
			}
			if (this.targetView == 'SideBarContainer') {
				SideBarContainer(SideBarContainerType.Embed) {
					Column() {
						ForEach([1, 2, 3], (item:number) => {
							Column({ space: 5 }) {
								Image($r('app.media.icon'))
									.width(50)
									.height(50)
								Text('Index0' + item)
									.fontSize(25)
							}
						})
					}
						.width('100%')
						.justifyContent(FlexAlign.SpaceEvenly)
						.backgroundColor(Color.Green)

					Column() {
						Text('SideBarContainer content')
							.fontSize(25)
					}
						.backgroundColor(Color.Orange)
				}
					.commonStyle()
					.attributeModifier(this._clickEffectSideBarContainerModifier)
			}
			if (this.targetView == 'Stack') {
				Stack() {
				}
					.commonStyle()
					.attributeModifier(this._clickEffectStackModifier)
			}
			if (this.targetView == 'Swiper') {
				Swiper() {
					ForEach([1, 2, 3], (item: string) => {
						Text('Swiper' + item)
							.width('90%')
							.height(50)
					}, (item:number) => item.toString())
				}
					.indicator(true)
					.backgroundColor(Color.White)
					.commonStyle()
					.attributeModifier(this._clickEffectSwiperModifier)
			}
			if (this.targetView == 'Tabs') {
				Tabs() {
					TabContent() {
						Column()
							.width('100%')
							.height('100%')
							.backgroundColor('#00CB87')
					}
				}
					.commonStyle()
					.attributeModifier(this._clickEffectTabsModifier)
			}
			if (this.targetView == 'TabContent') {
				Tabs() {
					TabContent() {
						Text('TabContent Test')
							.width('100%')
							.height('100%')
							.backgroundColor(Color.White)
					}
						.tabBar('Tabs1')
						.commonStyle()
						.attributeModifier(this._clickEffectTabContentModifier)
				}
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'WaterFlow') {
				WaterFlow() {
					ForEach([1, 2, 3, 4, 5, 6, 7, 8, 9], (item: number) => {
						FlowItem() {
							Column() {
								Text('WaterFlow' + item)
									.fontSize(12)
									.height('16')
								Image($r('app.media.icon'))
									.width(50)
									.height(50)
									.objectFit(ImageFit.Fill)
							}
						}
					}, (item:number) => item.toString())
				}
					.commonStyle()
					.attributeModifier(this._clickEffectWaterFlowModifier)
			}
			if (this.targetView == 'GridCol') {
				GridRow({ columns: 1, direction: GridRowDirection.Row }) {
					GridCol() {
						Row()
							.width('100%')
							.height('20vp')
					}
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._clickEffectGridColModifier)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'GridItem') {
				Grid() {
					GridItem() {
						Text('4')
							.backgroundColor(0xFAEEE0)
							.width('100%')
							.height('100%')
							.textAlign(TextAlign.Center)
					}
						.rowStart(1)
						.rowEnd(4)
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._clickEffectGridItemModifier)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'FlowItem') {
				WaterFlow() {
					ForEach([1, 2, 3, 4, 5, 6, 7, 8, 9], (item: number) => {
						FlowItem() {
							Column() {
								Text('WaterFlow' + item)
									.fontSize(12)
									.height('16')
								Image($r('app.media.icon'))
									.width(50)
									.height(50)
									.objectFit(ImageFit.Fill)
							}
						}
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._clickEffectFlowItemModifier)
					}, (item:number) => item.toString())
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'MenuItem') {
				Row() {
					Menu() {
						MenuItem({ startIcon: $r('app.media.icon'), content: 'MenuItem' })
							.commonStyle()
							.attributeModifier(this._clickEffectMenuItemModifier)
					}
						.backgroundColor(Color.Yellow)
						.width('100%')
						.height('100%')
				}
					.width('100%')
					.height('100%')
					.backgroundColor(Color.Green)
			}
			if (this.targetView == 'MenuItemGroup') {
				Row() {
					Menu() {
						MenuItemGroup({ header: 'MenuItemGroup' }) {
							MenuItem({ startIcon: $r('app.media.icon'), content: 'MenuItem' })
						}
							.commonStyle()
							.attributeModifier(this._clickEffectMenuItemGroupModifier)
					}
						.backgroundColor(Color.Yellow)
						.width('100%')
						.height('100%')
				}
					.width('100%')
					.height('100%')
					.backgroundColor(Color.Green)
			}
			if (this.targetView == 'CalendarPicker') {
				CalendarPicker({ hintRadius: 10, selected: new Date() })
					.commonStyle()
					.attributeModifier(this._clickEffectCalendarPickerModifier)
			}
			if (this.targetView == 'Canvas') {
				Canvas(new CanvasRenderingContext2D(new RenderingContextSettings(true)))
					.backgroundColor('#FFFF00')
					.commonStyle()
					.attributeModifier(this._clickEffectCanvasModifier)
			}
			if (this.targetView == 'FormLink') {
				FormLink({
					action: "router",
					abilityName: "EntryAbility",
					params: { 'message': 'testForRouter' }
				}) {
					Button("router event").width(120)
				}
					.commonStyle()
					.attributeModifier(this._clickEffectFormLinkModifier)
			}
			if (this.targetView == 'Hyperlink') {
				Hyperlink('https://example.com/', 'Go to the developer website') {
				}
					.commonStyle()
					.attributeModifier(this._clickEffectHyperlinkModifier)
			}
			if (this.targetView == 'Span') {
				Text() {
					Span('Span1')
						.commonStyle()
						.attributeModifier(this._clickEffectSpanModifier)
				}
			}
		}
		.width(this.parentWidth)
		.height(this.parentHeight)
		.backgroundColor(this.parentBackGroundColor || '#FFFF00')
		.key(this.parentComponentKey)
	}
}