/*
* Copyright (c) 2024 Huawei Device Co., Ltd.
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#include "common/common.h"
#include "manager/plugin_manager.h"
#include "calendarPicker/calendarPicker_date_test.h"
#include "dragEndPending/dragEndPending.h"
#include "swiperIndicator/swiperIndicator.h"
#include "pointerEvent/pointerEvent.h"
#include "swiperDigitIndicator/swiperDigitIndicator.h"
#include "getGestureParam/getGestureParam.h"
#include "layoutCallbackOnNodeHandle/layoutCallbackOnNodeHandle.h"
#include "swiperArrowStyle/swiperArrowStyle.h"
#include "arkuiXComponent/arkuiXComponent.h"
#include "accessibilityValue/accessibilityValue.h"
#include "surfaceHolder/surfaceHolder.h"
#include "textPickerCascade/textPickerCascade.h"
#include "customDialog/customDialog.h"

namespace ArkUICapiTest {
EXTERN_C_START
static napi_value Init(napi_env env, napi_value exports)
{
    OH_LOG_Print(LOG_APP, LOG_INFO, LOG_PRINT_DOMAIN, "Init", "Init begins");
    if ((env == nullptr) || (exports == nullptr)) {
        OH_LOG_Print(LOG_APP, LOG_ERROR, LOG_PRINT_DOMAIN, "Init", "env or exports is null");
        return nullptr;
    }

    napi_property_descriptor desc[] = {
        { "getContext", nullptr, PluginManager::GetContext, nullptr, nullptr, nullptr, napi_default, nullptr },
        { "testCalendarPickerDate", nullptr, CalendarPickerStartEndTest::CalendarPickerDateTest,
            nullptr, nullptr, nullptr, napi_default, nullptr},
         {"DragEndPendingTest_a", nullptr, DragEndPendingTest::DragEndPendingTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"DragEndPendingTest_a1", nullptr, DragEndPendingTest::DragEndPendingTest_a1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"DragEndPendingTest_b", nullptr, DragEndPendingTest::DragEndPendingTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"DragEndPendingTest_c", nullptr, DragEndPendingTest::DragEndPendingTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperIndicatorTest_a", nullptr, SwiperIndicatorTest::SwiperIndicatorTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperIndicatorTest_b", nullptr, SwiperIndicatorTest::SwiperIndicatorTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperIndicatorTest_a1", nullptr, SwiperIndicatorTest::SwiperIndicatorTest_a1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperIndicatorTest_b1", nullptr, SwiperIndicatorTest::SwiperIndicatorTest_b1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"PointerEventTest_a", nullptr, PointerEventTest::PointerEventTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"PointerEventTest_b", nullptr, PointerEventTest::PointerEventTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"PointerEventTest_a1", nullptr, PointerEventTest::PointerEventTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"PointerEventTest_b1", nullptr, PointerEventTest::PointerEventTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_a", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_b", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_c", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_d", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_e", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_e, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_f", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_f, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_g", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_g, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_h", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_h, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_i", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_i, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_j", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_j, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_k", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_k, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_l", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_l, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_b1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_b1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_c1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_c1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_d1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_d1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_e1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_e1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_f1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_f1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_g1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_g1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_h1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_h1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_i1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_i1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_j1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_j1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_k1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_k1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"swiperDigitIndicatorTest_l1", nullptr, swiperDigitIndicatorTest::swiperDigitIndicatorTest_l1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_a", nullptr, GetGestureParamTest::GetGestureParamTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_a1", nullptr, GetGestureParamTest::GetGestureParamTest_a1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_b", nullptr, GetGestureParamTest::GetGestureParamTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_c", nullptr, GetGestureParamTest::GetGestureParamTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_d", nullptr, GetGestureParamTest::GetGestureParamTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_e", nullptr, GetGestureParamTest::GetGestureParamTest_e, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_f", nullptr, GetGestureParamTest::GetGestureParamTest_f, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_g", nullptr, GetGestureParamTest::GetGestureParamTest_g, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_h", nullptr, GetGestureParamTest::GetGestureParamTest_h, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_i", nullptr, GetGestureParamTest::GetGestureParamTest_i, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_j", nullptr, GetGestureParamTest::GetGestureParamTest_j, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"GetGestureParamTest_j1", nullptr, GetGestureParamTest::GetGestureParamTest_j1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"LayoutCallbackOnNodeHandleTest_a", nullptr, LayoutCallbackOnNodeHandleTest::LayoutCallbackOnNodeHandleTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"LayoutCallbackOnNodeHandleTest_a1", nullptr, LayoutCallbackOnNodeHandleTest::LayoutCallbackOnNodeHandleTest_a1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"LayoutCallbackOnNodeHandleTest_b", nullptr, LayoutCallbackOnNodeHandleTest::LayoutCallbackOnNodeHandleTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"LayoutCallbackOnNodeHandleTest_b1", nullptr, LayoutCallbackOnNodeHandleTest::LayoutCallbackOnNodeHandleTest_b1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"LayoutCallbackOnNodeHandleTest_c", nullptr, LayoutCallbackOnNodeHandleTest::LayoutCallbackOnNodeHandleTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"LayoutCallbackOnNodeHandleTest_d", nullptr, LayoutCallbackOnNodeHandleTest::LayoutCallbackOnNodeHandleTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"LayoutCallbackOnNodeHandleTest_c1", nullptr, LayoutCallbackOnNodeHandleTest::LayoutCallbackOnNodeHandleTest_c1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"LayoutCallbackOnNodeHandleTest_d1", nullptr, LayoutCallbackOnNodeHandleTest::LayoutCallbackOnNodeHandleTest_d1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"NapiWrapEnhanceTest_d", nullptr, LayoutCallbackOnNodeHandleTest::NapiWrapEnhanceTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"NapiWrapEnhanceTest_d1", nullptr, LayoutCallbackOnNodeHandleTest::NapiWrapEnhanceTest_d1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_a", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_b", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_c", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_c1", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_c1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_c2", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_c2, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_d", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_d1", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_d1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_d2", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_d2, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_e", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_e, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_e1", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_e1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_f", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_f, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_f1", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_f1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_g", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_g, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_g1", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_g1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_h", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_h, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SwiperArrowStyleTest_h1", nullptr, SwiperArrowStyleTest::SwiperArrowStyleTest_h1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_a", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_b", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_c", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_d", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_e", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_e, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_f", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_f, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_g", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_g, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_g1", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_g1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_h", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_h, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_h1", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_h1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_i", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_i, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_j", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_j, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_i1", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_i1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"ArkuiXComponentTest_j1", nullptr, ArkuiXComponentTest::ArkuiXComponentTest_j1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_a", nullptr, AccessibilityValueTest::AccessibilityValueTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_a1", nullptr, AccessibilityValueTest::AccessibilityValueTest_a1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_b", nullptr, AccessibilityValueTest::AccessibilityValueTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_b1", nullptr, AccessibilityValueTest::AccessibilityValueTest_b1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_c", nullptr, AccessibilityValueTest::AccessibilityValueTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_c1", nullptr, AccessibilityValueTest::AccessibilityValueTest_c1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d", nullptr, AccessibilityValueTest::AccessibilityValueTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d1", nullptr, AccessibilityValueTest::AccessibilityValueTest_d1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d2", nullptr, AccessibilityValueTest::AccessibilityValueTest_d2, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d3", nullptr, AccessibilityValueTest::AccessibilityValueTest_d3, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d4", nullptr, AccessibilityValueTest::AccessibilityValueTest_d4, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d5", nullptr, AccessibilityValueTest::AccessibilityValueTest_d5, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d6", nullptr, AccessibilityValueTest::AccessibilityValueTest_d6, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d7", nullptr, AccessibilityValueTest::AccessibilityValueTest_d7, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d8", nullptr, AccessibilityValueTest::AccessibilityValueTest_d8, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_d9", nullptr, AccessibilityValueTest::AccessibilityValueTest_d9, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_e", nullptr, AccessibilityValueTest::AccessibilityValueTest_e, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_e1", nullptr, AccessibilityValueTest::AccessibilityValueTest_e1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_e2", nullptr, AccessibilityValueTest::AccessibilityValueTest_e2, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_f", nullptr, AccessibilityValueTest::AccessibilityValueTest_f, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_f1", nullptr, AccessibilityValueTest::AccessibilityValueTest_f1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_g", nullptr, AccessibilityValueTest::AccessibilityValueTest_g, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_g1", nullptr, AccessibilityValueTest::AccessibilityValueTest_g1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_h", nullptr, AccessibilityValueTest::AccessibilityValueTest_h, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_h1", nullptr, AccessibilityValueTest::AccessibilityValueTest_h1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_i", nullptr, AccessibilityValueTest::AccessibilityValueTest_i, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_i1", nullptr, AccessibilityValueTest::AccessibilityValueTest_i1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_j", nullptr, AccessibilityValueTest::AccessibilityValueTest_j, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_j1", nullptr, AccessibilityValueTest::AccessibilityValueTest_j1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_k", nullptr, AccessibilityValueTest::AccessibilityValueTest_k, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_k1", nullptr, AccessibilityValueTest::AccessibilityValueTest_k1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_l", nullptr, AccessibilityValueTest::AccessibilityValueTest_l, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_l1", nullptr, AccessibilityValueTest::AccessibilityValueTest_l1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_m", nullptr, AccessibilityValueTest::AccessibilityValueTest_m, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_m1", nullptr, AccessibilityValueTest::AccessibilityValueTest_m1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_n", nullptr, AccessibilityValueTest::AccessibilityValueTest_n, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_n1", nullptr, AccessibilityValueTest::AccessibilityValueTest_n1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_o", nullptr, AccessibilityValueTest::AccessibilityValueTest_o, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_o1", nullptr, AccessibilityValueTest::AccessibilityValueTest_o1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_p", nullptr, AccessibilityValueTest::AccessibilityValueTest_p, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"AccessibilityValueTest_p1", nullptr, AccessibilityValueTest::AccessibilityValueTest_p1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_a", nullptr, SurfaceHolderTest::SurfaceHolderTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_a1", nullptr, SurfaceHolderTest::SurfaceHolderTest_a1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_b", nullptr, SurfaceHolderTest::SurfaceHolderTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_c", nullptr, SurfaceHolderTest::SurfaceHolderTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_c1", nullptr, SurfaceHolderTest::SurfaceHolderTest_c1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_d", nullptr, SurfaceHolderTest::SurfaceHolderTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_e", nullptr, SurfaceHolderTest::SurfaceHolderTest_e, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_f", nullptr, SurfaceHolderTest::SurfaceHolderTest_f, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_e1", nullptr, SurfaceHolderTest::SurfaceHolderTest_e1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_f1", nullptr, SurfaceHolderTest::SurfaceHolderTest_f1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_g", nullptr, SurfaceHolderTest::SurfaceHolderTest_g, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_g1", nullptr, SurfaceHolderTest::SurfaceHolderTest_g1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_h", nullptr, SurfaceHolderTest::SurfaceHolderTest_h, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"SurfaceHolderTest_h1", nullptr, SurfaceHolderTest::SurfaceHolderTest_h1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_a", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_a1", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_a1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_b", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_b1", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_b1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_c", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_c1", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_c1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_d", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_d1", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_d1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_e", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_e, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_e1", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_e1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_f", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_f, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"TextPickerCascadeTest_f1", nullptr, TextPickerCascadeTest::TextPickerCascadeTest_f1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_a", nullptr, CustomDialogTest::CustomDialogTest_a, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_a1", nullptr, CustomDialogTest::CustomDialogTest_a1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_b", nullptr, CustomDialogTest::CustomDialogTest_b, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_c", nullptr, CustomDialogTest::CustomDialogTest_c, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_d", nullptr, CustomDialogTest::CustomDialogTest_d, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_b1", nullptr, CustomDialogTest::CustomDialogTest_b1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_c1", nullptr, CustomDialogTest::CustomDialogTest_c1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_d1", nullptr, CustomDialogTest::CustomDialogTest_d1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_e", nullptr, CustomDialogTest::CustomDialogTest_e, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_e1", nullptr, CustomDialogTest::CustomDialogTest_e1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_f", nullptr, CustomDialogTest::CustomDialogTest_f, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_f1", nullptr, CustomDialogTest::CustomDialogTest_f1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_g", nullptr, CustomDialogTest::CustomDialogTest_g, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_g1", nullptr, CustomDialogTest::CustomDialogTest_g1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_h", nullptr, CustomDialogTest::CustomDialogTest_h, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_h1", nullptr, CustomDialogTest::CustomDialogTest_h1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_i", nullptr, CustomDialogTest::CustomDialogTest_i, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_j", nullptr, CustomDialogTest::CustomDialogTest_j, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_k", nullptr, CustomDialogTest::CustomDialogTest_k, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_l", nullptr, CustomDialogTest::CustomDialogTest_l, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_m", nullptr, CustomDialogTest::CustomDialogTest_m, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_n", nullptr, CustomDialogTest::CustomDialogTest_n, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_i1", nullptr, CustomDialogTest::CustomDialogTest_i, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_j1", nullptr, CustomDialogTest::CustomDialogTest_j, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_k1", nullptr, CustomDialogTest::CustomDialogTest_k, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_l1", nullptr, CustomDialogTest::CustomDialogTest_l, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_m1", nullptr, CustomDialogTest::CustomDialogTest_m, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_n1", nullptr, CustomDialogTest::CustomDialogTest_n, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_o", nullptr, CustomDialogTest::CustomDialogTest_o, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_o1", nullptr, CustomDialogTest::CustomDialogTest_o1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_p", nullptr, CustomDialogTest::CustomDialogTest_p, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_p1", nullptr, CustomDialogTest::CustomDialogTest_p1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_q", nullptr, CustomDialogTest::CustomDialogTest_q, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_q1", nullptr, CustomDialogTest::CustomDialogTest_q1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_r", nullptr, CustomDialogTest::CustomDialogTest_r, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_r1", nullptr, CustomDialogTest::CustomDialogTest_r1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_s", nullptr, CustomDialogTest::CustomDialogTest_s, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_t", nullptr, CustomDialogTest::CustomDialogTest_t, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_s1", nullptr, CustomDialogTest::CustomDialogTest_s1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_t1", nullptr, CustomDialogTest::CustomDialogTest_t1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_u", nullptr, CustomDialogTest::CustomDialogTest_u, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_v", nullptr, CustomDialogTest::CustomDialogTest_v, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_w", nullptr, CustomDialogTest::CustomDialogTest_w, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_x", nullptr, CustomDialogTest::CustomDialogTest_x, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_y", nullptr, CustomDialogTest::CustomDialogTest_y, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_z", nullptr, CustomDialogTest::CustomDialogTest_z, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_u1", nullptr, CustomDialogTest::CustomDialogTest_u1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_v1", nullptr, CustomDialogTest::CustomDialogTest_v1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_w1", nullptr, CustomDialogTest::CustomDialogTest_w1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_x1", nullptr, CustomDialogTest::CustomDialogTest_x1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_y1", nullptr, CustomDialogTest::CustomDialogTest_y1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_z1", nullptr, CustomDialogTest::CustomDialogTest_z1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_A", nullptr, CustomDialogTest::CustomDialogTest_A, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_B", nullptr, CustomDialogTest::CustomDialogTest_B, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_C", nullptr, CustomDialogTest::CustomDialogTest_C, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_D", nullptr, CustomDialogTest::CustomDialogTest_D, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_A1", nullptr, CustomDialogTest::CustomDialogTest_A1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_B1", nullptr, CustomDialogTest::CustomDialogTest_B1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_C1", nullptr, CustomDialogTest::CustomDialogTest_C1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
         {"CustomDialogTest_D1", nullptr, CustomDialogTest::CustomDialogTest_D1, nullptr,
         nullptr, nullptr, napi_default, nullptr},
    };
    if (napi_define_properties(env, exports, sizeof(desc) / sizeof(desc[0]), desc) != napi_ok) {
        OH_LOG_Print(LOG_APP, LOG_ERROR, LOG_PRINT_DOMAIN, "Init", "napi_define_properties failed");
        return nullptr;
    }

    PluginManager::GetInstance()->Export(env, exports);
    return exports;
}
EXTERN_C_END

static napi_module nativerenderModule = {.nm_version = 1,
                                         .nm_flags = 0,
                                         .nm_filename = nullptr,
                                         .nm_register_func = Init,
                                         .nm_modname = "nativerender",
                                         .nm_priv = ((void *)0),
                                         .reserved = {0}};

extern "C" __attribute__((constructor)) void RegisterModule(void) { napi_module_register(&nativerenderModule); }
} // namespace ArkUICapiTest
